const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=v=>{let n=parseFloat(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null};
const state={view:'home',tab:'overview',gameId:null,game:null,games:[],players:[],history:[],refresh:2500,timer:null,syncBusy:false,lastSync:null,syncFailures:0,date:new Date().toLocaleDateString('en-CA',{timeZone:'America/New_York'})};
const api=async u=>{let r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(r.status);return r.json()};

const TEAM_COLORS={ARI:'#97233F',ATL:'#A71930',BAL:'#9E7C0C',BUF:'#C60C30',CAR:'#0085CA',CHI:'#C83803',CIN:'#FB4F14',CLE:'#FF3C00',DAL:'#869397',DEN:'#FB4F14',DET:'#0076B6',GB:'#FFB612',HOU:'#03202F',IND:'#002C5F',JAX:'#00A5B5',KC:'#E31837',LV:'#A5ACAF',LAC:'#0080C6',LA:'#FFA300',MIA:'#008E97',MIN:'#4F2683',NE:'#C60C30',NO:'#D3BC8D',NYG:'#0B2265',NYJ:'#125740',PHI:'#004C54',PIT:'#FFB612',SF:'#AA0000',SEA:'#69BE28',TB:'#D50A0A',TEN:'#4B92DB',WAS:'#FFB612'};
function applyTeamTheme(g){if(!g)return;let a=team(g,'away').abbr,h=team(g,'home').abbr,r=document.documentElement.style;r.setProperty('--away',TEAM_COLORS[a]||'#68d8ff');r.setProperty('--home',TEAM_COLORS[h]||'#c9ff3d');r.setProperty('--awayGlow',(TEAM_COLORS[a]||'#68d8ff')+'55');r.setProperty('--homeGlow',(TEAM_COLORS[h]||'#c9ff3d')+'55')}
function pctValue(v){let m=String(v??'').match(/([0-9.]+)%/);return m?Math.max(0,Math.min(100,+m[1])):null}
function compareMetric(g,label,key,...aliases){let a=team(g,'away'),h=team(g,'home'),av=getStat(g,a.abbr,key,...aliases),hv=getStat(g,h.abbr,key,...aliases),an=num(av),hn=num(hv),ap=pctValue(av),hp=pctValue(hv),max=Math.max(an||0,hn||0,1);let aw=ap??(an===null?8:Math.max(8,an/max*100)),hw=hp??(hn===null?8:Math.max(8,hn/max*100));return `<div class="compareRow"><div class="compareLabel">${esc(label)}</div><div class="compareValues"><strong style="color:var(--away)">${esc(av)}</strong><span>${esc(a.abbr)}</span><span class="vs">VS</span><span>${esc(h.abbr)}</span><strong style="color:var(--home)">${esc(hv)}</strong></div><div class="compareBars"><i class="awayBar" style="width:${aw}%"></i><i class="homeBar" style="width:${hw}%"></i></div></div>`}

function route(next,push=true){saveScroll();let entry={view:next.view||state.view,tab:next.tab||state.tab,gameId:next.gameId??state.gameId,date:next.date||state.date,scrollY:0};if(push){history.pushState(entry,'',`#${entry.view}/${entry.tab}${entry.gameId?'/'+entry.gameId:''}`)}Object.assign(state,entry);renderRoute();}
window.addEventListener('popstate',e=>{if(e.state){Object.assign(state,e.state);renderRoute(false);setTimeout(()=>scrollTo(0,e.state.scrollY||0),0)}});
function saveScroll(){let x=history.state;if(x)history.replaceState({...x,scrollY:scrollY},'')}
window.addEventListener('scroll',()=>{clearTimeout(window._st);window._st=setTimeout(saveScroll,120)});
function renderRoute(){ $$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view)); $$('#mainNav button').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view)); $('#topTitle').textContent=({home:'GAME CENTER',games:'NFL GAMES',players:'PLAYERS',analytics:'ANALYTICS',league:'LEAGUE HQ',warroom:'WAR ROOM',archive:'ARCHIVE',about:'ABOUT'})[state.view]||'GRIDIRON ATLAS';$('#backBtn').disabled=history.length<=1;if(state.view==='games')loadGames();if(state.view==='players')loadPlayerDb();if(state.view==='analytics')renderAnalytics();if(state.view==='league')loadLeague();if(state.view==='warroom')renderWarRoom();if(state.view==='archive')loadArchive();}
$('#backBtn').onclick=()=>history.back();$$('#mainNav button').forEach(b=>b.onclick=()=>route({view:b.dataset.view}));$$('[data-route]').forEach(b=>b.onclick=()=>route({view:b.dataset.route}));$$('[data-game-tab]').forEach(b=>b.onclick=()=>route({view:'games',tab:b.dataset.gameTab}));
$('#settingsBtn').onclick=()=>$('#settings').classList.add('open');$('#settingsClose').onclick=()=>$('#settings').classList.remove('open');$('#refreshRate').onchange=e=>{state.refresh=+e.target.value;startPolling()};
function phase(g){if(!g)return 'UNAVAILABLE';if(g.completed||g.state==='post')return 'FINAL';if(g.state==='in')return g.status?.toUpperCase()||'LIVE';return 'PREGAME'}
function team(g,side){return g?.teams?.find(t=>t.side===side)||{abbr:'—',name:'—',score:'0',logo:''}}
function hero(g){if(!g)return '<div class="empty">No game selected.</div>';let a=team(g,'away'),h=team(g,'home');return `<div class="eyebrow">${esc(g.source||'CONNECTED FEED')}</div><div class="score"><div class="team"><img src="${esc(a.logo||'')}" onerror="this.style.visibility='hidden'"><div><div class="teamName">${esc(a.name)}</div><div class="muted">${esc(a.abbr)}</div></div><div class="teamScore">${esc(a.score)}</div></div><div class="centerScore"><span class="phase">${esc(phase(g))}</span><div class="clock">${esc(g.clock)}</div><div class="muted">${g.period?'Q'+esc(g.period):esc(g.status)}</div></div><div class="team right"><div class="teamScore">${esc(h.score)}</div><div><div class="teamName">${esc(h.name)}</div><div class="muted">${esc(h.abbr)}</div></div><img src="${esc(h.logo||'')}" onerror="this.style.visibility='hidden'"></div></div>`}
function statMap(g,abbr){let o={};Object.entries(g?.team_stats?.[abbr]||{}).forEach(([k,v])=>o[k.toLowerCase().replace(/[^a-z0-9]/g,'')]=v);return o}
function getStat(g,abbr,...aliases){let m=statMap(g,abbr);for(let a of aliases){let k=a.toLowerCase().replace(/[^a-z0-9]/g,'');if(k in m)return m[k]}return '—'}
function playerGroups(g){let map={};for(let p of g?.players||[]){let key=`${p.team}|${p.name}`;if(!map[key])map[key]={...p,stats:{},categories:{}};map[key].categories[p.category||'stats']={...(p.stats||{})};for(let [k,v] of Object.entries(p.stats||{}))map[key].stats[`${p.category||'stats'}:${k}`]=v}return Object.values(map)}
function pickCategoryLeader(g,category,stat='YDS'){let best=null;for(let p of g?.players||[]){if(String(p.category).toLowerCase()!==category.toLowerCase())continue;let v=(p.stats||{})[stat],n=num(v);if(n!==null&&(!best||n>best.val))best={p,val:n,label:stat,value:v}}return best}
function playerImg(p){return p?.id?`https://a.espncdn.com/i/headshots/nfl/players/full/${encodeURIComponent(p.id)}.png`:''}
function leaderHtml(x){if(!x)return '<div class="empty">Not available yet.</div>';return `<div class="leader"><img class="headshot" src="${playerImg(x.p)}" onerror="this.style.display='none'"><div><b>${esc(x.p.name)}</b><div class="muted">${esc(x.p.team)} · ${esc(x.p.position||x.p.category)}</div><strong class="accent">${esc(x.value)} ${esc(x.label)}</strong></div></div>`}
function renderHome(){let g=state.game;applyTeamTheme(g);$('#homeHero').innerHTML=hero(g);if(!g)return;let a=team(g,'away').abbr,h=team(g,'home').abbr,sit=g.situation||{};let k=[['Possession',sit.possession],['Down & distance',sit.downDistanceText&&sit.downDistanceText!=='—'?sit.downDistanceText:(sit.down!=='—'?`${sit.down} & ${sit.distance}`:'—')],['Ball spot',sit.yardLine],['Plays captured',g.plays?.length||0]];$('#homeKpis').innerHTML=k.map(x=>`<div class="kpi"><small>${esc(x[0])}</small><strong>${esc(x[1])}</strong></div>`).join('');let leaders=[pickCategoryLeader(g,'passing','YDS'),pickCategoryLeader(g,'rushing','YDS'),pickCategoryLeader(g,'receiving','YDS')].filter(Boolean);$('#homeLeaders').innerHTML=leaders.length?leaders.slice(0,3).map(leaderHtml).join('<hr style="border:0;border-top:1px solid var(--line)">'):'<div class="empty">Player leaders will appear when box-score data arrives.</div>';let d=g.drives?.at(-1);$('#homeDrive').innerHTML=d?`<b>${esc(d.team)} · ${esc(d.result)}</b><p>${esc(d.yards??'—')} yards · ${esc(d.plays??'—')} plays · ${esc(d.time??'—')}</p>`:'<div class="empty">No drive data yet.</div>';let p=g.plays?.at(-1);$('#homePlay').innerHTML=p?`<b>Q${esc(p.period)} ${esc(p.clock)}</b><p>${esc(p.text)}</p>`:'<div class="empty">No play-by-play yet.</div>'}
async function loadSelected(id,{restart=true}={}){if(state.syncBusy)return;state.syncBusy=true;try{const g=await api('/api/game?id='+encodeURIComponent(id)+'&_='+Date.now());state.game=g;state.gameId=id;state.lastSync=Date.now();state.syncFailures=0;renderHome();if(state.view==='games')renderGame();if(state.view==='analytics')renderAnalytics();if(state.view==='warroom')renderWarRoom();renderSyncStatus();}catch(e){state.syncFailures++;renderSyncStatus();console.error('Live sync failed',e)}finally{state.syncBusy=false;if(restart)startPolling()}}
async function loadGames(){try{$('#gameDate').value=state.date;let d=await api('/api/games?date='+state.date);state.games=d.games||[];$('#gameStrip').innerHTML=state.games.length?state.games.map(g=>{let a=team(g,'away'),h=team(g,'home');return `<button class="gameCard ${g.id===state.gameId?'active':''}" data-gid="${esc(g.id)}"><div class="gameTeams">${esc(a.abbr)} ${esc(a.score)} · ${esc(h.abbr)} ${esc(h.score)}</div><div class="gameMeta">${esc(g.status)}</div></button>`}).join(''):'<div class="empty">No NFL games returned for this date.</div>';$$('[data-gid]').forEach(b=>b.onclick=()=>{route({view:'games',tab:'overview',gameId:b.dataset.gid});loadSelected(b.dataset.gid)});if(state.gameId&&!state.game)loadSelected(state.gameId);else renderGame()}catch(e){$('#gameStrip').innerHTML='<div class="empty">Could not load the NFL schedule.</div>'}}
$('#gameDate').onchange=e=>route({view:'games',date:e.target.value});function shiftDay(n){let d=new Date(state.date+'T12:00:00');d.setDate(d.getDate()+n);route({view:'games',date:d.toLocaleDateString('en-CA')})}$('#prevDay').onclick=()=>shiftDay(-1);$('#nextDay').onclick=()=>shiftDay(1);
$$('#gameTabs button').forEach(b=>b.onclick=()=>route({view:'games',tab:b.dataset.tab}));
function renderGame(){let g=state.game;applyTeamTheme(g);$('#gameHero').innerHTML=hero(g);$$('#gameTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));let w=$('#gameWorkspace');if(!g){w.innerHTML='<div class="empty">Select a game above.</div>';return}if(state.tab==='overview')w.innerHTML=overview(g);if(state.tab==='team')w.innerHTML=teamStats(g);if(state.tab==='players')w.innerHTML=playerBox(g);if(state.tab==='drives')w.innerHTML=driveChart(g);if(state.tab==='plays')w.innerHTML=plays(g);wirePlayerClicks()}
function overview(g){applyTeamTheme(g);let a=team(g,'away'),h=team(g,'home'),sit=g.situation||{},p=g.plays?.at(-1),d=g.drives?.at(-1);return `<div class="pulse"><div class="pulseTeam awayPulse"><small>${esc(a.abbr)}</small><strong>${esc(a.score)}</strong><span>${esc(a.name)}</span></div><div class="pulseNow"><small>RIGHT NOW</small><b>${esc(sit.downDistanceText||g.status||'—')}</b><span>${esc(sit.possession||'—')} ball · ${esc(sit.yardLine||'—')}</span></div><div class="pulseTeam homePulse"><small>${esc(h.abbr)}</small><strong>${esc(h.score)}</strong><span>${esc(h.name)}</span></div></div><div class="essentialPanel">${compareMetric(g,'Total yards','Total Yards')}${compareMetric(g,'Passing yards','Passing')}${compareMetric(g,'Rushing yards','Rushing')}${compareMetric(g,'First downs','1st Downs')}${compareMetric(g,'Turnovers','Turnovers')}${compareMetric(g,'3rd down','3rd down efficiency')}</div><div class="grid g2 glanceGrid"><div class="card"><div class="cardHead"><b>Latest play</b><span class="badge">LIVE</span></div><div class="cardBody bigEvent">${p?`<small>Q${esc(p.period)} · ${esc(p.clock)}</small><strong>${esc(p.text)}</strong>`:'<div class="empty">Waiting for the next play.</div>'}</div></div><div class="card"><div class="cardHead"><b>Current drive</b></div><div class="cardBody bigEvent">${d?`<small>${esc(d.team)}</small><strong>${esc(d.result)}</strong><span>${esc(d.yards??'—')} yards · ${esc(d.plays??'—')} plays · ${esc(d.time??'—')}</span>`:'<div class="empty">No drive data yet.</div>'}</div></div></div><div class="grid g2 glanceGrid"><div class="card"><div class="cardHead"><b>Score flow</b></div><div class="cardBody chart">${scoreChart(g)}</div></div><div class="card"><div class="cardHead"><b>Top performers</b></div><div class="cardBody grid">${[pickCategoryLeader(g,'passing','YDS'),pickCategoryLeader(g,'rushing','YDS'),pickCategoryLeader(g,'receiving','YDS')].map(leaderHtml).join('')}</div></div></div>`}
function teamStats(g){applyTeamTheme(g);return `<div class="sectionLead"><div><span class="eyebrow">ESSENTIAL TEAM STATS</span><h2>Who is controlling the game?</h2></div><div class="teamKey"><b style="color:var(--away)">${esc(team(g,'away').abbr)}</b><span>vs</span><b style="color:var(--home)">${esc(team(g,'home').abbr)}</b></div></div><div class="essentialPanel teamEssential">${compareMetric(g,'Total yards','Total Yards')}${compareMetric(g,'Yards / play','Yards Per Play','Yards/Play')}${compareMetric(g,'Passing','Passing')}${compareMetric(g,'Rushing','Rushing')}${compareMetric(g,'First downs','1st Downs')}${compareMetric(g,'3rd down','3rd down efficiency')}${compareMetric(g,'Red zone','Red Zone (Made-Att)','Red Zone')}${compareMetric(g,'Turnovers','Turnovers')}</div>`}
function playerBox(g){let ps=playerGroups(g);if(ps.length)return `<div class="card"><div class="cardHead"><b>Verified live box score</b><span class="badge">FEED</span></div><div class="cardBody"><div id="boxRows">${playerRows(ps)}</div></div></div>`;let roster=g?.roster_players||[];return `<div class="card"><div class="cardHead"><b>Pregame player board</b><span class="badge">BASELINE</span></div><div class="cardBody"><p class="muted">Live player statistics have not arrived yet. Showing the verified embedded matchup roster instead.</p>${baselineRows(roster)}</div></div>`}
function playerRows(ps){return ps.length?`<div class="tableWrap"><table class="dataTable"><thead><tr><th>Player</th><th>Team</th><th>Pos</th><th>Verified stat line</th></tr></thead><tbody>${ps.map(p=>`<tr><td><button class="linkBtn playerOpen" data-player="${esc(p.name)}">${esc(p.name)}</button></td><td>${esc(p.team)}</td><td>${esc(p.position)}</td><td>${Object.entries(p.stats).map(([k,v])=>`${esc(k)} ${esc(v)}`).join(' · ')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No player box-score data yet.</div>'}
function baselineRows(ps){return ps.length?`<div class="tableWrap"><table class="dataTable"><thead><tr><th>Player</th><th>Team</th><th>Pos</th><th>Unit</th><th>Verified baseline</th></tr></thead><tbody>${ps.map(p=>`<tr><td><button class="linkBtn baselineOpen" data-player="${esc(p.name)}">${esc(p.name)}</button></td><td>${esc(p.team)}</td><td>${esc(p.position)}</td><td>${esc(p.unit||'—')}</td><td>${esc(p.baseline||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No verified roster data is available for this matchup.</div>'}
function plays(g){return `<div class="card"><div class="cardBody feed">${(g.plays||[]).length?[...g.plays].reverse().map(p=>`<div class="feedItem"><small>Q${esc(p.period)} · ${esc(p.clock)} · ${esc(p.team)}</small><b>${esc(p.text)}</b></div>`).join(''):'<div class="empty">No play-by-play available yet.</div>'}</div></div>`}
function driveChart(g){return `<div class="card"><div class="cardHead"><b>Drive chart</b><span class="badge">FEED</span></div><div class="cardBody"><div class="field"></div><div style="margin-top:14px">${(g.drives||[]).length?g.drives.map((d,i)=>`<div class="feedItem"><small>Drive ${i+1} · ${esc(d.team)}</small><b>${esc(d.result)}</b><div class="driveBar" style="width:${Math.max(4,Math.min(100,Math.abs(num(d.yards)||8)))}%"></div><span class="muted">${esc(d.yards??'—')} yards · ${esc(d.plays??'—')} plays · ${esc(d.time??'—')}</span></div>`).join(''):'<div class="empty">No drive data yet.</div>'}</div></div></div>`}
function svgBase(content){return `<svg viewBox="0 0 700 240" role="img"><line x1="45" y1="205" x2="680" y2="205" stroke="#ffffff22"/><line x1="45" y1="20" x2="45" y2="205" stroke="#ffffff22"/>${content}</svg>`}
function scoreChart(g){let s=g.scoring_plays||[],a=team(g,'away'),h=team(g,'home');if(!s.length)return '<div class="empty">Scoring flow appears after the first score.</div>';let pts=[[0,0,0]],as=0,hs=0;s.forEach((x,i)=>{as=num(x.awayScore)??as;hs=num(x.homeScore)??hs;pts.push([i+1,as,hs])});let max=Math.max(7,...pts.flatMap(x=>x.slice(1))),X=i=>45+i*(635/(pts.length-1||1)),Y=v=>205-v*(175/max);let path=(idx,color)=>`<polyline fill="none" stroke="${color}" stroke-width="4" points="${pts.map((p,i)=>`${X(i)},${Y(p[idx])}`).join(' ')}"/>`;return svgBase(path(1,'var(--away)')+path(2,'var(--home)'))+`<div class="legend"><span>${esc(a.abbr)} score</span><span>${esc(h.abbr)} score</span></div>`}
function quarterChart(g){let a=team(g,'away'),h=team(g,'home'),la=g.linescores?.[a.abbr]||[],lh=g.linescores?.[h.abbr]||[],n=Math.max(4,la.length,lh.length);let vals=[...Array(n)].map((_,i)=>[num(la[i])||0,num(lh[i])||0]);let max=Math.max(7,...vals.flat());let bars=vals.map((v,i)=>{let x=70+i*(580/n),w=Math.min(32,220/n),ha=v[0]*150/max,hh=v[1]*150/max;return `<rect x="${x}" y="${205-ha}" width="${w}" height="${ha}" rx="4" fill="var(--away)"/><rect x="${x+w+5}" y="${205-hh}" width="${w}" height="${hh}" rx="4" fill="var(--home)"/><text x="${x}" y="225" fill="#8d98a5" font-size="11">Q${i+1}</text>`}).join('');return svgBase(bars)+`<div class="legend"><span>${esc(a.abbr)}</span><span>${esc(h.abbr)}</span></div>`}
function derived(g){let a=team(g,'away').abbr,h=team(g,'home').abbr;let rows=[];for(let ab of [a,h]){let plays=(g.plays||[]).filter(p=>p.team===ab),drives=(g.drives||[]).filter(d=>d.team===ab),score=num(team(g,team(g,'away').abbr===ab?'away':'home').score);let yards=num(getStat(g,ab,'Total Yards')),offplays=num(getStat(g,ab,'Total Plays','Offensive Plays'));rows.push({ab,plays:plays.length,drives:drives.length,ypp:yards!==null&&offplays?yards/offplays:null,ppd:score!==null&&drives.length?score/drives.length:null,explosive:plays.length?plays.filter(p=>Math.abs(num(p.statYardage)||0)>=20).length/plays.length*100:null,threeOut:drives.length?drives.filter(d=>(num(d.plays)??99)<=3&&/punt/i.test(d.result||'')).length/drives.length*100:null})}return rows}
function renderAnalytics(){let g=state.game;if(!g){$('#analyticsBody').innerHTML='<div class="empty">Select a game in NFL Games first.</div>';return}applyTeamTheme(g);let d=derived(g),a=team(g,'away'),h=team(g,'home'),sit=g.situation||{};let metric=(label,key,digits=2)=>`<div class="simpleMetric"><small>${label}</small><div><strong style="color:var(--away)">${d[0]?.[key]===null?'—':d[0]?.[key]?.toFixed(digits)}</strong><span>${esc(a.abbr)}</span><i>vs</i><span>${esc(h.abbr)}</span><strong style="color:var(--home)">${d[1]?.[key]===null?'—':d[1]?.[key]?.toFixed(digits)}</strong></div></div>`;$('#analyticsBody').innerHTML=`<div class="sectionLead"><div><span class="eyebrow">GAME AT A GLANCE</span><h2>What is happening right now?</h2></div><div class="liveSituation"><small>${esc(sit.possession||'—')} POSSESSION</small><b>${esc(sit.downDistanceText||'—')}</b><span>${esc(sit.yardLine||'—')}</span></div></div><div class="analyticsScore"><div style="border-color:var(--away)"><small>${esc(a.abbr)}</small><strong style="color:var(--away)">${esc(a.score)}</strong></div><span>Q${esc(g.period||'—')} · ${esc(g.clock)}</span><div style="border-color:var(--home)"><small>${esc(h.abbr)}</small><strong style="color:var(--home)">${esc(h.score)}</strong></div></div><div class="grid g2 simpleMetrics">${metric('Yards per play','ypp')}${metric('Points per drive','ppd')}</div><div class="essentialPanel compactCompare">${compareMetric(g,'Total yards','Total Yards')}${compareMetric(g,'First downs','1st Downs')}${compareMetric(g,'Turnovers','Turnovers')}${compareMetric(g,'3rd down','3rd down efficiency')}</div><div class="grid g2 glanceGrid"><div class="card"><div class="cardHead"><b>Score flow</b></div><div class="cardBody chart">${scoreChart(g)}</div></div><div class="card"><div class="cardHead"><b>Quarter scoring</b></div><div class="cardBody chart">${quarterChart(g)}</div></div></div><div class="analyticsWall"><div class="card"><div class="cardHead"><b>Drive efficiency</b><span class="badge derived">ƒ DERIVED</span></div><div class="cardBody">${metric('Explosive play rate','explosive',1)}${metric('Three-and-out rate','threeOut',1)}</div></div><div class="card"><div class="cardHead"><b>Production split</b></div><div class="cardBody">${compareMetric(g,'Passing yards','Passing')}${compareMetric(g,'Rushing yards','Rushing')}${compareMetric(g,'Red zone','Red Zone (Made-Att)','Red Zone')}</div></div><div class="card"><div class="cardHead"><b>Live leaders</b></div><div class="cardBody leaderStack">${[pickCategoryLeader(g,'passing','YDS'),pickCategoryLeader(g,'rushing','YDS'),pickCategoryLeader(g,'receiving','YDS')].map(leaderHtml).join('')}</div></div><div class="card"><div class="cardHead"><b>Defensive snapshot</b></div><div class="cardBody">${compareMetric(g,'Sacks','Sacks')}${compareMetric(g,'Turnovers','Turnovers')}${compareMetric(g,'3rd down','3rd down efficiency')}</div></div></div>`}

let leagueTab='standings', leagueData=null;
function fmtRank(n){return n?`#${n}`:'—'}
function statNum(o,...keys){for(const k of keys){const v=o?.[k];const n=num(v);if(n!==null)return n}return null}
function leaderCards(groups){if(!groups?.length)return '<div class="empty">Season leader feed unavailable right now.</div>';return `<div class="leaderGrid">${groups.slice(0,8).map(g=>`<div class="leaderBoard"><div class="cardHead"><b>${esc(g.name||g.displayName||'Leader')}</b><span class="badge">SEASON</span></div><div class="cardBody">${(g.leaders||[]).slice(0,5).map((x,i)=>`<div class="rankRow"><strong>${i+1}</strong><div><b>${esc(x.name||'—')}</b><small>${esc(x.team||'')} · ${esc(x.value??'—')}</small></div></div>`).join('')||'<div class="empty">No entries.</div>'}</div></div>`).join('')}</div>`}
function renderLeague(){const b=$('#leagueBody');if(!b)return;const d=leagueData;if(!d){b.innerHTML='<div class="empty">Loading league intelligence…</div>';return}
const standings=d.standings||[], teams=d.teams||[], power=d.power||[];
const row=(x,i,extra='')=>`<tr><td>${esc(x.atlasRank||x.rank||i+1)}</td><td><span class="teamSwatch" style="background:${TEAM_COLORS[x.abbr]||'#667'}"></span><b>${esc(x.abbr)}</b> ${esc(x.name||'')}</td><td>${esc(x.record||'—')}</td><td>${esc(x.winPct??'—')}</td><td>${esc(x.diff??'—')}</td>${extra}</tr>`;
const miniTable=(title,rows)=>`<div class="divisionCard"><div class="divisionHead"><div><small>${esc(title.split(' ')[0])}</small><b>${esc(title)}</b></div><span>${rows[0]?esc(rows[0].abbr):'—'} LEADS</span></div><div class="divisionRows">${rows.map((x,i)=>`<div class="divisionRow"><strong>${i+1}</strong><span class="teamSwatch" style="background:${TEAM_COLORS[x.abbr]||'#667'}"></span><b>${esc(x.abbr)}</b><em>${esc(x.record||'—')}</em><small>${esc(x.diff??'—')} DIFF</small></div>`).join('')}</div></div>`;
if(leagueTab==='standings'){b.innerHTML=`<div class="leagueHero"><div><span class="eyebrow">NFL SNAPSHOT</span><h2>${standings.length} teams tracked</h2><p>Records, point differential and season position from the league feed.</p></div><div class="leaguePulse"><b>${esc(d.season||'2026')}</b><small>REGULAR SEASON</small></div></div><div class="card"><div class="cardBody"><div class="tableWrap"><table class="dataTable megaTable"><thead><tr><th>Rank</th><th>Team</th><th>W-L-T</th><th>Win %</th><th>Diff</th></tr></thead><tbody>${standings.map((x,i)=>row(x,i)).join('')}</tbody></table></div></div></div>`}
else if(leagueTab==='divisions'){b.innerHTML=`<div class="leagueHero"><div><span class="eyebrow">8 DIVISIONS · 32 TEAMS</span><h2>Division control center</h2><p>Every team grouped where the playoff race actually happens. The first row in each card is the current statistical division leader.</p></div></div><div class="divisionGrid">${Object.entries(d.divisions||{}).map(([k,v])=>miniTable(k,v)).join('')}</div>`}
else if(leagueTab==='conferences'){b.innerHTML=`<div class="leagueHero"><div><span class="eyebrow">AFC + NFC</span><h2>Conference command</h2><p>Conference-wide records and current ordering. Early-season sample size matters.</p></div></div><div class="conferenceGrid">${['AFC','NFC'].map(c=>`<div class="conferenceCard"><div class="conferenceTitle"><b>${c}</b><span>${(d.conferences?.[c]||[]).length} TEAMS</span></div>${(d.conferences?.[c]||[]).map((x,i)=>`<div class="conferenceRow"><strong>${i+1}</strong><span class="teamSwatch" style="background:${TEAM_COLORS[x.abbr]||'#667'}"></span><b>${esc(x.abbr)}</b><span>${esc(x.record||'—')}</span><small>${esc(x.diff??'—')} DIFF</small></div>`).join('')}</div>`).join('')}</div>`}
else if(leagueTab==='power'){b.innerHTML=`<div class="leagueHero"><div><span class="eyebrow">ATLAS INDEX</span><h2>Performance rankings</h2><p>Transparent Atlas calculation using record first, then point differential and verified stored-game efficiency. This is not a prediction.</p></div><span class="ngsStatus">ƒ DERIVED</span></div><div class="powerGrid">${power.map((x,i)=>`<div class="powerRow" style="--tc:${TEAM_COLORS[x.abbr]||'#667'}"><strong>${i+1}</strong><span class="teamSwatch" style="background:var(--tc)"></span><div><b>${esc(x.abbr)} · ${esc(x.name||'')}</b><small>${esc(x.record||'—')} · ${esc(x.division||'')}</small></div><em>${esc(x.atlasIndex??'—')}</em></div>`).join('')}</div>`}
else if(leagueTab==='teams'){b.innerHTML=`<div class="leagueHero"><div><span class="eyebrow">TEAM LAB</span><h2>32-team intelligence directory</h2><p>Stored-game offense and defense metrics stay sample-labeled rather than pretending to be complete season totals.</p></div></div><div class="teamMatrix">${teams.map((x,i)=>`<div class="teamTile" style="--tc:${TEAM_COLORS[x.abbr]||'#667'}"><div class="teamTileTop"><img src="${esc(x.logo||'')}" onerror="this.style.display='none'"><div><small>${esc(x.abbr)}</small><b>${esc(x.name||x.abbr)}</b></div><strong>${esc((power.find(p=>p.abbr===x.abbr)||{}).atlasRank?'#'+(power.find(p=>p.abbr===x.abbr)||{}).atlasRank:'—')}</strong></div><div class="miniStats"><span><small>Games sampled</small><b>${esc(x.games||0)}</b></span><span><small>PF/G</small><b>${x.ppg==null?'—':x.ppg.toFixed(1)}</b></span><span><small>YDS/G</small><b>${x.ypg==null?'—':x.ypg.toFixed(1)}</b></span><span><small>YDS Allowed</small><b>${x.yapg==null?'—':x.yapg.toFixed(1)}</b></span></div></div>`).join('')||'<div class="empty">Team sample builds as Atlas stores games.</div>'}</div>`}
else if(leagueTab==='teamleaders'){let tls=d.teamLeaders||{};b.innerHTML=`<div class="leagueHero"><div><span class="eyebrow">TEAM LEADERS</span><h2>Who drives each roster?</h2><p>Season leader entries are grouped back to their teams from the provider feed.</p></div></div><div class="teamLeaderGrid">${Object.entries(tls).filter(([,v])=>v?.length).map(([ab,v])=>`<div class="leaderBoard teamLeaderCard" style="--tc:${TEAM_COLORS[ab]||'#667'}"><div class="cardHead"><b>${esc(ab)}</b><span class="badge">TEAM LEADERS</span></div><div class="cardBody">${v.slice(0,6).map(x=>`<div class="teamLeaderRow"><small>${esc(x.category)}</small><b>${esc(x.name||'—')}</b><strong>${esc(x.value??'—')}</strong></div>`).join('')}</div></div>`).join('')||'<div class="empty">Team leader feed unavailable right now.</div>'}</div>`}
else if(leagueTab==='leaders'){b.innerHTML=`<div class="leagueHero"><div><span class="eyebrow">NFL LEADERS</span><h2>League production leaders</h2><p>Passing, rushing, receiving and other categories when supplied by the season feed.</p></div></div>${leaderCards(d.leaders)}`}
else if(leagueTab==='defense'){let ts=[...teams].sort((a,b)=>(a.yapg??1e9)-(b.yapg??1e9));b.innerHTML=`<div class="leagueHero"><div><span class="eyebrow">DEFENSIVE COMMAND</span><h2>Stops, takeaways and yards allowed</h2><p>Verified Atlas stored-game defensive profile. Sample sizes are shown.</p></div></div><div class="leaderGrid">${ts.slice(0,16).map((x,i)=>`<div class="defCard" style="--tc:${TEAM_COLORS[x.abbr]||'#667'}"><small>${fmtRank(i+1)} · ${esc(x.abbr)} · ${esc(x.games||0)} G</small><strong>${x.yapg==null?'—':x.yapg.toFixed(1)}</strong><span>yards allowed / game</span><div><b>${x.takeaways??'—'}</b><small>takeaways in Atlas sample</small></div></div>`).join('')}</div>`}
else if(leagueTab==='race'){let afc=d.conferences?.AFC||[],nfc=d.conferences?.NFC||[];b.innerHTML=`<div class="leagueHero"><div><span class="eyebrow">CHAMPIONSHIP PICTURE</span><h2>The road through each conference</h2><p>Factual standings view — no betting odds or outcome probabilities.</p></div></div><div class="raceGrid">${[['AFC',afc],['NFC',nfc]].map(([c,rs])=>`<div class="raceCard"><div class="conferenceTitle"><b>${c}</b><span>CURRENT ORDER</span></div>${rs.slice(0,7).map((x,i)=>`<div class="seedRow"><strong>${i+1}</strong><span class="teamSwatch" style="background:${TEAM_COLORS[x.abbr]||'#667'}"></span><div><b>${esc(x.abbr)}</b><small>${esc(x.division||'')}</small></div><em>${esc(x.record||'—')}</em></div>`).join('')}</div>`).join('')}</div>`}
else {b.innerHTML=`<div class="leagueHero ngsHero"><div><span class="eyebrow">NEXT GEN LAB</span><h2>Tracking-grade workspace</h2><p>Atlas never invents tracking data. NGS metrics appear only when a verified source exposes them.</p></div><span class="ngsStatus">SOURCE-GATED</span></div><div class="ngsGrid">${[['CPOE','Completion % over expected'],['Air Yards','Depth of target'],['RYOE','Rush yards over expected'],['Separation','Receiver separation'],['Time to Throw','QB release time'],['Top Speed','Tracking speed'],['Pressure','QB pressure metrics'],['Route Data','Route / coverage intelligence']].map(x=>`<div class="ngsCard"><small>${x[1]}</small><strong>—</strong><b>${x[0]}</b><span>Awaiting verified tracking source</span></div>`).join('')}</div>`}}

async function loadLeague(){try{leagueData=await api('/api/league?_='+Date.now());renderLeague()}catch(e){$('#leagueBody').innerHTML='<div class="empty">League feed unavailable. Game Center remains live.</div>'}}
document.addEventListener('click',e=>{let b=e.target.closest('[data-ltab]');if(!b)return;leagueTab=b.dataset.ltab;$$('#leagueTabs button').forEach(x=>x.classList.toggle('active',x===b));renderLeague()});

async function loadPlayerDb(){try{let d=await api('/api/players');state.players=d.players||[];let teams=[...new Set(state.players.map(x=>x.team).filter(Boolean))].sort(),pos=[...new Set(state.players.map(x=>x.position).filter(Boolean))].sort();$('#playerTeam').innerHTML='<option value="">All teams</option>'+teams.map(x=>`<option>${esc(x)}</option>`).join('');$('#playerPos').innerHTML='<option value="">All positions</option>'+pos.map(x=>`<option>${esc(x)}</option>`).join('');filterPlayers()}catch(e){$('#playerDb').innerHTML='<div class="empty">Player database unavailable.</div>'}}
function filterPlayers(){let q=$('#playerSearch').value.toLowerCase(),t=$('#playerTeam').value,p=$('#playerPos').value;let arr=state.players.filter(x=>(!q||x.name.toLowerCase().includes(q))&&(!t||x.team===t)&&(!p||x.position===p));$('#playerDb').innerHTML=arr.length?`<div class="tableWrap"><table class="dataTable"><thead><tr><th>Player</th><th>Team</th><th>Pos</th><th>Stored games</th></tr></thead><tbody>${arr.map(x=>`<tr><td><button class="linkBtn dbPlayer" data-name="${esc(x.name)}">${esc(x.name)}</button></td><td>${esc(x.team)}</td><td>${esc(x.position)}</td><td>${x.games?.length||0}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No matching players.</div>';$$('.dbPlayer').forEach(b=>b.onclick=()=>showProfile(state.players.find(x=>x.name===b.dataset.name)))}
$('#playerSearch').oninput=filterPlayers;$('#playerTeam').onchange=filterPlayers;$('#playerPos').onchange=filterPlayers;
function showProfile(p){if(!p)return;let games=p.games||[];$('#playerProfile').innerHTML=`<div class="card"><div class="cardBody profile"><img class="profilePortrait" src="${playerImg(p)}" onerror="this.style.display='none'"><div><div class="eyebrow">${esc(p.team)} · ${esc(p.position)}</div><h2 class="title" style="font-size:38px">${esc(p.name)}</h2>${p.baseline?`<div class="kpi" style="margin-bottom:12px"><small>Verified baseline</small><strong style="font-size:15px">${esc(p.baseline)}</strong></div>`:''}<div class="grid g3">${games.slice(-6).map(g=>`<div class="kpi"><small>${esc(g.status)}</small><strong style="font-size:15px">${Object.entries(g.stats||{}).slice(0,4).map(([k,v])=>`${esc(k)} ${esc(v)}`).join(' · ')||'—'}</strong></div>`).join('')}</div></div></div></div>`}
function wirePlayerClicks(){$$('.playerOpen').forEach(b=>b.onclick=()=>{let p=playerGroups(state.game).find(x=>x.name===b.dataset.player);route({view:'players'});setTimeout(()=>showProfile(p),100)});$$('.baselineOpen').forEach(b=>b.onclick=()=>{let p=(state.game?.roster_players||[]).find(x=>x.name===b.dataset.player);route({view:'players'});setTimeout(()=>showProfile({...p,games:[]}),100)})}

function driveYardsChart(g){let ds=(g.drives||[]).filter(d=>num(d.yards)!==null).slice(-12);if(!ds.length)return '<div class="empty">Drive yardage appears as drives are recorded.</div>';let max=Math.max(10,...ds.map(d=>Math.abs(num(d.yards)||0)));return `<div class="driveViz">${ds.map((d,i)=>{let y=num(d.yards)||0,c=d.team===team(g,'away').abbr?'var(--away)':'var(--home)',w=Math.max(4,Math.abs(y)/max*100);return `<div class="driveVizRow"><small>D${i+1} · ${esc(d.team)}</small><div><i style="width:${w}%;background:${c}"></i></div><b>${esc(y)} YDS</b></div>`}).join('')}</div>`}
function playYardageChart(g){let ps=(g.plays||[]).filter(p=>num(p.statYardage)!==null).slice(-20);if(!ps.length)return '<div class="empty">Play yardage appears when the feed supplies it.</div>';let max=Math.max(10,...ps.map(p=>Math.abs(num(p.statYardage)||0)));return `<div class="sparkBars">${ps.map(p=>{let y=num(p.statYardage)||0,c=p.team===team(g,'away').abbr?'var(--away)':'var(--home)',h=Math.max(4,Math.abs(y)/max*92);return `<span title="${esc(p.team)} ${esc(y)} yards"><i style="height:${h}%;background:${c}"></i><small>${esc(y)}</small></span>`}).join('')}</div><div class="chartNote">Last ${ps.length} plays with verified yardage · bar height = absolute yards</div>`}
function explosiveFeed(g){let ps=(g.plays||[]).filter(p=>Math.abs(num(p.statYardage)||0)>=20).slice(-8).reverse();return ps.length?`<div class="impactFeed">${ps.map(p=>`<div><b style="color:${p.team===team(g,'away').abbr?'var(--away)':'var(--home)'}">${esc(p.team)} · ${esc(p.statYardage)} YDS</b><span>Q${esc(p.period)} ${esc(p.clock)} · ${esc(p.text)}</span></div>`).join('')}</div>`:'<div class="empty">No verified 20+ yard plays captured yet.</div>'}
function scoringTimeline(g){let s=g.scoring_plays||[];return s.length?`<div class="scoreTimeline">${s.map((x,i)=>`<div><strong>${i+1}</strong><span><b>${esc(x.team||'SCORE')}</b>${esc(x.text||x.type||'Scoring play')}</span><em>${esc(x.awayScore??'—')}–${esc(x.homeScore??'—')}</em></div>`).join('')}</div>`:'<div class="empty">Scoring sequence appears after the first score.</div>'}
function renderWarRoom(){let b=$('#warRoomBody'),g=state.game;if(!b)return;if(!g){b.innerHTML='<div class="empty">Select a game first.</div>';return}applyTeamTheme(g);let a=team(g,'away'),h=team(g,'home'),sit=g.situation||{},d=derived(g),last=g.plays?.at(-1),drive=g.drives?.at(-1);let stat=(label,key,aliases=[])=>`<div class="warStat"><small>${esc(label)}</small><div><b style="color:var(--away)">${esc(getStat(g,a.abbr,key,...aliases))}</b><span>${esc(a.abbr)}</span><i>VS</i><span>${esc(h.abbr)}</span><b style="color:var(--home)">${esc(getStat(g,h.abbr,key,...aliases))}</b></div></div>`;b.innerHTML=`<div class="warHeader"><div class="warTeam awayWar"><small>${esc(a.abbr)}</small><strong>${esc(a.score)}</strong><span>${esc(a.name)}</span></div><div class="warNow"><span class="eyebrow">LIVE COMMAND</span><h3>${esc(sit.downDistanceText||g.status||'—')}</h3><b>${esc(sit.possession||'—')} · ${esc(sit.yardLine||'—')}</b><small>Q${esc(g.period||'—')} · ${esc(g.clock)}</small></div><div class="warTeam homeWar"><small>${esc(h.abbr)}</small><strong>${esc(h.score)}</strong><span>${esc(h.name)}</span></div></div><div class="warTicker"><div><small>LATEST PLAY</small><b>${esc(last?.text||'Waiting for play-by-play')}</b></div><div><small>CURRENT DRIVE</small><b>${drive?`${esc(drive.team)} · ${esc(drive.yards??'—')} yds · ${esc(drive.plays??'—')} plays · ${esc(drive.time??'—')}`:'—'}</b></div></div><div class="warStatGrid">${stat('Total yards','Total Yards')}${stat('Yards / play','Yards Per Play',['Yards/Play'])}${stat('Passing','Passing')}${stat('Rushing','Rushing')}${stat('First downs','1st Downs')}${stat('3rd down','3rd down efficiency')}${stat('Red zone','Red Zone (Made-Att)',['Red Zone'])}${stat('Turnovers','Turnovers')}</div><div class="grid g2 warCharts"><div class="card"><div class="cardHead"><b>Drive yardage</b><span class="badge">LIVE</span></div><div class="cardBody">${driveYardsChart(g)}</div></div><div class="card"><div class="cardHead"><b>Play-by-play yardage pulse</b><span class="badge">LIVE</span></div><div class="cardBody">${playYardageChart(g)}</div></div><div class="card"><div class="cardHead"><b>Scoring sequence</b></div><div class="cardBody">${scoringTimeline(g)}</div></div><div class="card"><div class="cardHead"><b>Explosive plays</b><span class="badge derived">20+ YDS</span></div><div class="cardBody">${explosiveFeed(g)}</div></div></div><div class="grid g3 warBottom"><div class="card"><div class="cardHead"><b>Passing leader</b></div><div class="cardBody">${leaderHtml(pickCategoryLeader(g,'passing','YDS'))}</div></div><div class="card"><div class="cardHead"><b>Rushing leader</b></div><div class="cardBody">${leaderHtml(pickCategoryLeader(g,'rushing','YDS'))}</div></div><div class="card"><div class="cardHead"><b>Receiving leader</b></div><div class="cardBody">${leaderHtml(pickCategoryLeader(g,'receiving','YDS'))}</div></div></div>`}

async function loadArchive(){try{let d=await api('/api/archive');let gs=d.games||[];$('#archiveList').innerHTML=gs.length?gs.map(g=>`<button class="gameCard archiveOpen" data-id="${esc(g.id)}"><div class="gameTeams">${esc((g.teams||[]).map(t=>t.abbr+' '+t.score).join(' · '))}</div><div class="gameMeta">${esc(g.status)} · ${esc(g.id)}</div></button>`).join(''):'<div class="empty">No archived games yet.</div>';$$('.archiveOpen').forEach(b=>b.onclick=()=>openArchive(b.dataset.id))}catch(e){$('#archiveList').innerHTML='<div class="empty">Archive unavailable.</div>'}}
async function openArchive(id){let [g,h]=await Promise.all([api('/api/game?id='+encodeURIComponent(id)),api('/api/history?id='+encodeURIComponent(id))]);$('#archiveReplay').innerHTML=`<div class="hero">${hero(g)}</div><div class="grid g2" style="margin-top:14px"><div class="card"><div class="cardHead"><b>Final team stats</b></div><div class="cardBody">${teamStats(g)}</div></div><div class="card"><div class="cardHead"><b>Saved progression</b></div><div class="cardBody feed">${(h.snapshots||[]).map(x=>`<div class="feedItem"><small>${new Date(x.t*1000).toLocaleTimeString()}</small><b>${Object.entries(x.scores||{}).map(([k,v])=>`${esc(k)} ${esc(v)}`).join(' · ')}</b></div>`).join('')||'<div class="empty">No snapshots.</div>'}</div></div></div>`}
async function health(){try{let h=await api('/api/health');if(!state.lastSync)$('#healthText').textContent=`${h.provider} · ${h.database}`;$('#setProvider').textContent=h.provider;$('#setDb').textContent=h.database;$('#setCollector').textContent=`${h.collector_seconds}s cadence`;$('#setLast').textContent=h.last?.collector?new Date(h.last.collector*1000).toLocaleTimeString():'—'}catch(e){$('#healthText').textContent='CONNECTION DEGRADED'}}
function renderSyncStatus(){const el=document.getElementById('healthText');if(!el)return;const syncAge=state.lastSync?Math.max(0,Math.round((Date.now()-state.lastSync)/1000)):null;const phase=state.game?.state==='in'?'LIVE':(state.game?.completed||state.game?.state==='post'?'FINAL':'PREGAME');const feed=state.game?.feed_age_seconds;if(state.syncFailures)el.textContent=`SYNC RETRYING · ${state.syncFailures} failed`;else if(feed!==null&&feed!==undefined)el.textContent=`${phase} · FEED ${feed}s OLD · checked ${syncAge??0}s ago`;else if(syncAge!==null)el.textContent=`${phase} · checked ${syncAge}s ago`; }
function startPolling(){clearInterval(state.timer);if(!state.gameId)return;const tick=()=>loadSelected(state.gameId,{restart:false});state.timer=setInterval(tick,Math.max(2000,state.refresh));}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.gameId)loadSelected(state.gameId)});window.addEventListener('focus',()=>{if(state.gameId)loadSelected(state.gameId)});
document.addEventListener('keydown',e=>{if(e.altKey&&e.key==='ArrowLeft'){e.preventDefault();history.back()}if(e.altKey&&e.key.toLowerCase()==='g'){e.preventDefault();route({view:'games'})}});
function initialRoute(){let parts=location.hash.replace(/^#/,'').split('/').filter(Boolean);let views=new Set(['home','games','players','analytics','league','warroom','archive','about']);let tabs=new Set(['overview','team','players','plays','drives']);return {view:views.has(parts[0])?parts[0]:'home',tab:tabs.has(parts[1])?parts[1]:'overview',gameId:parts[2]||null,date:state.date,scrollY:0}}
(async function init(){let initial=initialRoute();Object.assign(state,initial);history.replaceState(initial,'',`#${initial.view}/${initial.tab}${initial.gameId?'/'+initial.gameId:''}`);renderRoute();health();try{let d=await api('/api/games?date='+state.date);state.games=d.games||[];let first=state.games.find(x=>x.state==='in')||state.games[0];if(first)await loadSelected(first.id)}catch(e){}renderHome();setInterval(health,30000)})();
