
function atlasLineChart(rows,xKey,yKey,label){
 rows=(rows||[]).map(r=>({x:r?.[xKey],y:Number(r?.[yKey])})).filter(r=>r.x!=null&&Number.isFinite(r.y));
 if(rows.length<2)return `<div class="empty">More verified data is needed for this trend.</div>`;
 let W=760,H=230,P=28,ys=rows.map(r=>r.y),mn=Math.min(...ys),mx=Math.max(...ys);if(mx===mn){mx+=1;mn-=1}
 let X=i=>P+i*(W-P*2)/Math.max(1,rows.length-1),Y=v=>H-P-(v-mn)*(H-P*2)/(mx-mn);
 let pts=rows.map((r,i)=>`${X(i)},${Y(r.y)}`).join(" "),area=`${P},${H-P} ${pts} ${W-P},${H-P}`;
 let grid=[0,.25,.5,.75,1].map(t=>`<line class="gridline" x1="${P}" x2="${W-P}" y1="${P+t*(H-P*2)}" y2="${P+t*(H-P*2)}"/>`).join("");
 let dots=rows.map((r,i)=>`<circle class="dot" cx="${X(i)}" cy="${Y(r.y)}" r="4"><title>${String(r.x)} · ${r.y}</title></circle>`).join("");
 return `<div class="chart-title"><b>${label}</b><span>${rows.length} VERIFIED POINTS</span></div><svg class="atlas-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="${label}">${grid}<polygon class="area" points="${area}"/><polyline class="line" points="${pts}"/>${dots}<text class="axis" x="${P}" y="${H-5}">${String(rows[0].x)}</text><text class="axis" text-anchor="end" x="${W-P}" y="${H-5}">${String(rows[rows.length-1].x)}</text></svg>`}

const $=s=>document.querySelector(s),esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let S={page:"home",events:[],fighters:[],letter:"a",compare:[]};
const pages=[["home","Home","⌂"],["events","Events","▤"],["fighters","Fighters","◉"],["stats","Stat Lab","⌁"],["compare","Compare","⇄"],["diagnostics","Data Doctor","✓"]];
async function api(u){let r=await fetch(u,{cache:"no-store"}),x=await r.json();if(!r.ok||x.ok===false)throw Error(x.error||"UFC data request failed");return x}
function shell(title,body){$("#app").innerHTML=`<div class="shell"><aside class="side"><a class="logo" href="/"><i>A</i><div><b>UFC ATLAS</b><small>COMBAT SPORTS INTELLIGENCE</small></div></a><nav>${pages.map(([k,n,i])=>`<button data-icon="${i}" class="${S.page===k?"active":""}" onclick="go('${k}')">${n}</button>`).join("")}</nav><div class="source">STAT SOURCE<br>UFCSTATS<br><br>NO BETTING FEATURES<br>NO FABRICATED DATA</div></aside><main class="main"><header class="top"><b>${esc(title).toUpperCase()}</b><span class="badge">VERIFIED STATS MODE</span></header><div class="page">${body}</div></main></div>`}
function go(p){S.page=p;render()}
async function boot(){shell("UFC ATLAS",`<div class="loading">CONNECTING TO UFC STATISTICS…</div>`);try{let e=await api("/api/ufc/events");S.events=e.events||[]}catch(e){S.error=e.message}render()}
function render(){if(S.page==="home")home();if(S.page==="events")events();if(S.page==="fighters")fighters();if(S.page==="stats")statLab();if(S.page==="compare")compare();if(S.page==="diagnostics")doctor()}
function home(){let recent=S.events.slice(0,8);shell("Home",`<div class="hero"><span class="ey">ATLAS / UFC</span><h1>FIGHT <em>INTELLIGENCE.</em></h1><p>A separate combat-sports engine built around verified fighter records and UFC fight statistics. No sportsbook data, no fake live feed, and no invented metrics.</p></div><div class="grid"><section class="card wide"><h3>EVENT BOARD</h3>${eventRows(recent)}</section><section class="card"><h3>UFC ATLAS IDENTITY</h3><div class="octagon"><span class="a">STRIKING</span><span class="b">GRAPPLING</span></div><div class="receipt">Red + ice/cyan visual system is exclusive to UFC ATLAS. Career statistics are displayed as reported by UFCStats.</div></section></div>`)}
function eventRows(rows){return rows.length?rows.map(x=>`<div class="event" onclick="openEvent('${x.id}')"><div><b>${esc(x.name)}</b><span>${esc(x.date)}</span><small>${esc(x.location)}</small></div><em>OPEN CARD →</em></div>`).join(""):`<div class="empty">${esc(S.error||"No events returned.")}</div>`}
function events(){shell("Events",`<div class="hero"><span class="ey">EVENT ARCHIVE</span><h1>UFC <em>EVENTS.</em></h1><p>Event cards and recorded results from UFCStats.</p></div><section class="card full">${eventRows(S.events)}</section>`)}
async function openEvent(id){shell("Event",`<div class="loading">LOADING FIGHT CARD…</div>`);try{let x=await api("/api/ufc/event?id="+id),e=x;S.page="events";shell(e.name,`<div class="hero"><span class="ey">${esc(e.date)} · ${esc(e.location)}</span><h1>${esc(e.name)}</h1></div><section class="card full"><h3>FIGHT CARD</h3>${(e.fights||[]).map(f=>`<div class="fight" onclick="openFight('${f.id}')"><div class="fighthead"><b>${esc(f.fighter1)}</b><span class="vs">VS</span><b>${esc(f.fighter2)}</b></div><div class="meta">${esc(f.weight_class)} · ${esc(f.method)} · R${esc(f.round)} ${esc(f.time)}</div></div>`).join("")||'<div class="empty">No fight rows returned.</div>'}</section>`)}catch(e){alert(e.message);events()}}
function letters(){return `<div class="letters">${"abcdefghijklmnopqrstuvwxyz".split("").map(x=>`<button onclick="loadLetter('${x}')">${x.toUpperCase()}</button>`).join("")}</div>`}
async function loadLetter(l){S.letter=l;shell("Fighters",`<div class="loading">LOADING ${l.toUpperCase()} FIGHTERS…</div>`);try{let x=await api("/api/ufc/fighters?letter="+l);S.fighters=x.fighters||[];fighters()}catch(e){S.fighters=[];S.error=e.message;fighters()}}
function fighters(){shell("Fighters",`<div class="hero"><span class="ey">FIGHTER DATABASE</span><h1>FIGHTER <em>HUBS.</em></h1><p>Search by name or browse UFCStats fighter records alphabetically.</p></div><section class="card full"><input id="fq" class="search" placeholder="Search fighter name or nickname…">${letters()}<div id="fout">${fighterRows(S.fighters)}</div></section>`);let q=$("#fq"),t;q.oninput=()=>{clearTimeout(t);t=setTimeout(async()=>{if(q.value.trim().length<2){$("#fout").innerHTML=fighterRows(S.fighters);return}try{let x=await api("/api/ufc/search?q="+encodeURIComponent(q.value));$("#fout").innerHTML=fighterRows(x.results||[])}catch(e){$("#fout").innerHTML=`<div class="empty">${esc(e.message)}</div>`}},250)};if(!S.fighters.length)loadLetter(S.letter)}
function fighterRows(rows){return rows.length?rows.map(f=>`<div class="fighter" onclick="openFighter('${f.id}')"><div><b>${esc(f.name)}</b><span>${esc(f.nickname)} · ${esc(f.weight)} · ${esc(f.stance)}</span></div><div class="record">${esc(f.wins)}-${esc(f.losses)}-${esc(f.draws)}</div></div>`).join(""):`<div class="empty">No fighters returned.</div>`}
async function openFighter(id){try{let x=await api("/api/ufc/fighter?id="+id),p=x.fighter;document.body.insertAdjacentHTML("beforeend",`<div class="drawerback" id="drawer" onclick="if(event.target===this)this.remove()"><section class="drawer"><button class="close" onclick="$('#drawer').remove()">×</button><span class="ey">FIGHTER PROFILE</span><h2>${esc(p.name)}</h2><div class="nick">${esc(p.nickname)}</div><p>${esc(p.record)} · ${esc(p.weight)} · ${esc(p.stance)}</p><div class="stats">${Object.entries(p.stats||{}).map(([k,v])=>`<div class="stat"><span>${esc(k)}</span><b>${esc(v||"—")}</b></div>`).join("")}</div><h3>PHYSICAL PROFILE</h3><div class="stats">${["height","weight","reach","stance","dob"].map(k=>`<div class="stat"><span>${k.toUpperCase()}</span><b>${esc(p[k]||"—")}</b></div>`).join("")}</div><h3>RECENT FIGHTS</h3>${(p.fights||[]).map(f=>`<div class="fight"><b>${esc(f.result)}</b> · ${esc(f.event)}<div class="meta">${esc(f.method)} · R${esc(f.round)} ${esc(f.time)}</div></div>`).join("")}</section></div>`)}catch(e){alert(e.message)}}
async function statLab(){shell("Stat Lab",`<div class="hero"><span class="ey">STYLE PROFILE</span><h1>STAT <em>LAB.</em></h1><p>Search a fighter and visualize the career metrics UFCStats publishes: striking pace, accuracy/defense, takedowns and submission attempts.</p></div><section class="card full"><input id="sq" class="search" placeholder="Search fighter…"><div id="sres"></div></section><div id="slab"></div>`);let q=$("#sq"),t;q.oninput=()=>{clearTimeout(t);t=setTimeout(async()=>{if(q.value.trim().length<2)return;let x=await api("/api/ufc/search?q="+encodeURIComponent(q.value));$("#sres").innerHTML=(x.results||[]).slice(0,8).map(f=>`<div class="fighter" onclick="labFighter('${f.id}')"><b>${esc(f.name)}</b><span class="record">${esc(f.wins)}-${esc(f.losses)}-${esc(f.draws)}</span></div>`).join("")},250)}}
async function labFighter(id){let x=await api("/api/ufc/fighter?id="+id),p=x.fighter,s=p.stats||{};let pct=v=>{let n=parseFloat(v);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):0};$("#slab").innerHTML=`<div class="grid"><section class="card half"><h3>${esc(p.name)} · CAREER PROFILE</h3>${["StrAcc","StrDef","TDAcc","TDDef"].map(k=>`<div class="meter"><span>${k}</span><div class="track"><i style="width:${pct(s[k])}%"></i></div><b>${esc(s[k]||"—")}</b></div>`).join("")}</section><section class="card half"><h3>PACE / GRAPPLING</h3><div class="stats">${["SLpM","SApM","TDAvg","SubAvg"].map(k=>`<div class="stat"><span>${k}</span><b>${esc(s[k]||"—")}</b></div>`).join("")}</div></section><section class="card full"><h3>FIGHTER SHAPE · VERIFIED CAREER METRICS</h3>${ufcShape(p)}</section></div>`}
function ufcShape(p){let s=p.stats||{},vals=[["STR ACC",parseFloat(s.StrAcc)],["STR DEF",parseFloat(s.StrDef)],["TD ACC",parseFloat(s.TDAcc)],["TD DEF",parseFloat(s.TDDef)]];if(vals.filter(x=>Number.isFinite(x[1])).length<3)return '<div class="empty">More verified percentage metrics are needed.</div>';let cx=180,cy=150,R=105,pts=vals.map((x,i)=>{let a=-Math.PI/2+i*Math.PI/2,v=Math.max(0,Math.min(100,Number.isFinite(x[1])?x[1]:0))/100;return [cx+Math.cos(a)*R*v,cy+Math.sin(a)*R*v]});let outer=vals.map((x,i)=>{let a=-Math.PI/2+i*Math.PI/2;return `${cx+Math.cos(a)*R},${cy+Math.sin(a)*R}`}).join(" ");return `<svg class="fightshape" viewBox="0 0 360 300" role="img" aria-label="Verified fighter statistical shape"><polygon class="shapegrid" points="${outer}"/><polygon class="shapedata" points="${pts.map(x=>x.join(",")).join(" ")}"/>${vals.map((x,i)=>{let a=-Math.PI/2+i*Math.PI/2,tx=cx+Math.cos(a)*(R+28),ty=cy+Math.sin(a)*(R+22);return `<text x="${tx}" y="${ty}" text-anchor="middle">${x[0]} ${Number.isFinite(x[1])?x[1]+"%":"—"}</text>`}).join("")}</svg>`}
function compare(){shell("Compare",`<div class="hero"><span class="ey">SIDE-BY-SIDE</span><h1>FIGHTER <em>COMPARE.</em></h1><p>Compare two career statistical profiles. This is descriptive analysis, not a prediction or betting tool.</p></div><section class="card full"><input id="cq" class="search" placeholder="Search fighter to add…"><div id="cres"></div></section><div class="compare">${compareCards()}</div>`);let q=$("#cq"),t;q.oninput=()=>{clearTimeout(t);t=setTimeout(async()=>{if(q.value.trim().length<2)return;let x=await api("/api/ufc/search?q="+encodeURIComponent(q.value));$("#cres").innerHTML=(x.results||[]).slice(0,8).map(f=>`<div class="fighter" onclick="addCompare('${f.id}')"><b>${esc(f.name)}</b><span>ADD</span></div>`).join("")},250)}}
async function addCompare(id){if(S.compare.length>=2||S.compare.some(x=>x.id===id))return;let x=await api("/api/ufc/fighter?id="+id);S.compare.push(x.fighter);compare()}
function compareCards(){return S.compare.length?S.compare.map((p,i)=>`<section class="card"><button class="close" onclick="S.compare.splice(${i},1);compare()">×</button><h2>${esc(p.name)}</h2><p>${esc(p.record)}</p><div class="stats">${Object.entries(p.stats||{}).map(([k,v])=>`<div class="stat"><span>${esc(k)}</span><b>${esc(v||"—")}</b></div>`).join("")}</div></section>`).join(""):'<section class="card full empty">Add up to two fighters.</section>'}
async function openFight(id){try{let x=await api("/api/ufc/fight?id="+id);document.body.insertAdjacentHTML("beforeend",`<div class="drawerback" id="drawer" onclick="if(event.target===this)this.remove()"><section class="drawer"><button class="close" onclick="$('#drawer').remove()">×</button><span class="ey">FIGHT DETAIL</span><h2>${esc((x.fighters||[]).join(" vs "))}</h2><div class="receipt">${esc(x.note)}</div><h3>UFCSTATS ROUND ROWS</h3>${(x.round_rows||[]).map(r=>`<div class="fight">${r.map(c=>esc(c)).join(" · ")}</div>`).join("")||'<div class="empty">No detailed rows returned.</div>'}</section></div>`)}catch(e){alert(e.message)}}
async function doctor(){shell("Data Doctor",`<div class="loading">CHECKING UFC DATA PIPELINE…</div>`);try{let x=await api("/api/ufc/diagnostics");shell("Data Doctor",`<div class="hero"><span class="ey">BACKGROUND CHECK</span><h1>DATA <em>DOCTOR.</em></h1><p>ATLAS checks the UFC source independently from NFL and MLB.</p></div><div class="grid">${Object.entries(x.checks||{}).map(([k,v])=>`<section class="card half"><h3>${esc(k)}</h3><div class="stat"><span>STATUS</span><b>${v.ok?"PASS":"FAIL"}</b></div><p>${esc(v.count)} rows · ${esc(v.source||v.error)}</p></section>`).join("")}<section class="card full receipt">${(x.principles||[]).map(esc).join(" · ")}</section></div>`)}catch(e){shell("Data Doctor",`<div class="empty">${esc(e.message)}</div>`)}}
boot();