const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=v=>{let n=parseFloat(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null};
const state={view:'home',tab:'overview',gameId:null,game:null,games:[],players:[],history:[],refresh:5000,timer:null,syncBusy:false,lastSync:null,syncFailures:0,date:new Date().toLocaleDateString('en-CA',{timeZone:'America/New_York'})};
const api=async u=>{let r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(r.status);return r.json()};
function route(next,push=true){saveScroll();let entry={view:next.view||state.view,tab:next.tab||state.tab,gameId:next.gameId??state.gameId,date:next.date||state.date,scrollY:0};if(push){history.pushState(entry,'',`#${entry.view}/${entry.tab}${entry.gameId?'/'+entry.gameId:''}`)}Object.assign(state,entry);renderRoute();}
window.addEventListener('popstate',e=>{if(e.state){Object.assign(state,e.state);renderRoute(false);setTimeout(()=>scrollTo(0,e.state.scrollY||0),0)}});
function saveScroll(){let x=history.state;if(x)history.replaceState({...x,scrollY:scrollY},'')}
window.addEventListener('scroll',()=>{clearTimeout(window._st);window._st=setTimeout(saveScroll,120)});
function renderRoute(){ $$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view)); $$('#mainNav button').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view)); $('#topTitle').textContent=({home:'GAME CENTER',games:'NFL GAMES',players:'PLAYERS',analytics:'ANALYTICS',archive:'ARCHIVE'})[state.view]||'GRIDIRON ATLAS';$('#backBtn').disabled=history.length<=1;if(state.view==='games')loadGames();if(state.view==='players')loadPlayerDb();if(state.view==='analytics')renderAnalytics();if(state.view==='archive')loadArchive();}
$('#backBtn').onclick=()=>history.back();$$('#mainNav button').forEach(b=>b.onclick=()=>route({view:b.dataset.view}));$$('[data-route]').forEach(b=>b.onclick=()=>route({view:b.dataset.route}));$$('[data-game-tab]').forEach(b=>b.onclick=()=>route({view:'games',tab:b.dataset.gameTab}));
$('#settingsBtn').onclick=()=>$('#settings').classList.add('open');$('#settingsClose').onclick=()=>$('#settings').classList.remove('open');$('#refreshRate').onchange=e=>{state.refresh=+e.target.value;startPolling()};
function phase(g){if(!g)return 'UNAVAILABLE';if(g.completed||g.state==='post')return 'FINAL';if(g.state==='in')return g.status?.toUpperCase()||'LIVE';return 'PREGAME'}
function team(g,side){return g?.teams?.find(t=>t.side===side)||{abbr:'—',name:'—',score:'0',logo:''}}
function hero(g){if(!g)return '<div class="empty">No game selected.</div>';let a=team(g,'away'),h=team(g,'home');return `<div class="eyebrow">${esc(g.source||'CONNECTED FEED')}</div><div class="score"><div class="team"><img src="${esc(a.logo||'')}" onerror="this.style.visibility='hidden'"><div><div class="teamName">${esc(a.name)}</div><div class="muted">${esc(a.abbr)}</div></div><div class="teamScore">${esc(a.score)}</div></div><div class="centerScore"><span class="phase">${esc(phase(g))}</span><div class="clock">${esc(g.clock)}</div><div class="muted">${g.period?'Q'+esc(g.period):esc(g.status)}</div></div><div class="team right"><div class="teamScore">${esc(h.score)}</div><div><div class="teamName">${esc(h.name)}</div><div class="muted">${esc(h.abbr)}</div></div><img src="${esc(h.logo||'')}" onerror="this.style.visibility='hidden'"></div></div>`}
function statMap(g,abbr){let o={};Object.entries(g?.team_stats?.[abbr]||{}).forEach(([k,v])=>o[k.toLowerCase().replace(/[^a-z0-9]/g,'')]=v);return o}
function getStat(g,abbr,...aliases){let m=statMap(g,abbr);for(let a of aliases){let k=a.toLowerCase().replace(/[^a-z0-9]/g,'');if(k in m)return m[k]}return '—'}
function playerGroups(g){let map={};for(let p of g?.players||[]){let key=`${p.team}|${p.name}`;if(!map[key])map[key]={...p,stats:{}};Object.assign(map[key].stats,p.stats||{})}return Object.values(map)}
function pickLeader(g,keys){let best=null;for(let p of playerGroups(g)){for(let [k,v] of Object.entries(p.stats)){if(keys.some(x=>k.toLowerCase().includes(x))){let n=num(v);if(n!==null&&(!best||n>best.val))best={p,val:n,label:k,value:v}}}}return best}
function playerImg(p){return p?.id?`https://a.espncdn.com/i/headshots/nfl/players/full/${encodeURIComponent(p.id)}.png`:''}
function leaderHtml(x){if(!x)return '<div class="empty">Not available yet.</div>';return `<div class="leader"><img class="headshot" src="${playerImg(x.p)}" onerror="this.style.display='none'"><div><b>${esc(x.p.name)}</b><div class="muted">${esc(x.p.team)} · ${esc(x.p.position||x.p.category)}</div><strong class="accent">${esc(x.value)} ${esc(x.label)}</strong></div></div>`}
function renderHome(){let g=state.game;$('#homeHero').innerHTML=hero(g);if(!g)return;let a=team(g,'away').abbr,h=team(g,'home').abbr,sit=g.situation||{};let k=[['Possession',sit.possession],['Down & distance',sit.down!=='—'?`${sit.down} & ${sit.distance}`:'—'],['Ball spot',sit.yardLine],['Plays captured',g.plays?.length||0]];$('#homeKpis').innerHTML=k.map(x=>`<div class="kpi"><small>${esc(x[0])}</small><strong>${esc(x[1])}</strong></div>`).join('');let leaders=[pickLeader(g,['passingyards','passyds','yds']),pickLeader(g,['rushingyards','rushyds']),pickLeader(g,['receivingyards','recyds'])].filter(Boolean);$('#homeLeaders').innerHTML=leaders.length?leaders.slice(0,3).map(leaderHtml).join('<hr style="border:0;border-top:1px solid var(--line)">'):'<div class="empty">Player leaders will appear when box-score data arrives.</div>';let d=g.drives?.at(-1);$('#homeDrive').innerHTML=d?`<b>${esc(d.team)} · ${esc(d.result)}</b><p>${esc(d.yards??'—')} yards · ${esc(d.plays??'—')} plays · ${esc(d.time??'—')}</p>`:'<div class="empty">No drive data yet.</div>';let p=g.plays?.at(-1);$('#homePlay').innerHTML=p?`<b>Q${esc(p.period)} ${esc(p.clock)}</b><p>${esc(p.text)}</p>`:'<div class="empty">No play-by-play yet.</div>'}
async function loadSelected(id,{restart=true}={}){if(state.syncBusy)return;state.syncBusy=true;try{const g=await api('/api/game?id='+encodeURIComponent(id)+'&_='+Date.now());state.game=g;state.gameId=id;state.lastSync=Date.now();state.syncFailures=0;renderHome();if(state.view==='games')renderGame();if(state.view==='analytics')renderAnalytics();renderSyncStatus();}catch(e){state.syncFailures++;renderSyncStatus();console.error('Live sync failed',e)}finally{state.syncBusy=false;if(restart)startPolling()}}
async function loadGames(){try{$('#gameDate').value=state.date;let d=await api('/api/games?date='+state.date);state.games=d.games||[];$('#gameStrip').innerHTML=state.games.length?state.games.map(g=>{let a=team(g,'away'),h=team(g,'home');return `<button class="gameCard ${g.id===state.gameId?'active':''}" data-gid="${esc(g.id)}"><div class="gameTeams">${esc(a.abbr)} ${esc(a.score)} · ${esc(h.abbr)} ${esc(h.score)}</div><div class="gameMeta">${esc(g.status)}</div></button>`}).join(''):'<div class="empty">No NFL games returned for this date.</div>';$$('[data-gid]').forEach(b=>b.onclick=()=>{route({view:'games',tab:'overview',gameId:b.dataset.gid});loadSelected(b.dataset.gid)});if(state.gameId&&!state.game)loadSelected(state.gameId);else renderGame()}catch(e){$('#gameStrip').innerHTML='<div class="empty">Could not load the NFL schedule.</div>'}}
$('#gameDate').onchange=e=>route({view:'games',date:e.target.value});function shiftDay(n){let d=new Date(state.date+'T12:00:00');d.setDate(d.getDate()+n);route({view:'games',date:d.toLocaleDateString('en-CA')})}$('#prevDay').onclick=()=>shiftDay(-1);$('#nextDay').onclick=()=>shiftDay(1);
$$('#gameTabs button').forEach(b=>b.onclick=()=>route({view:'games',tab:b.dataset.tab}));
function renderGame(){let g=state.game;$('#gameHero').innerHTML=hero(g);$$('#gameTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));let w=$('#gameWorkspace');if(!g){w.innerHTML='<div class="empty">Select a game above.</div>';return}if(state.tab==='overview')w.innerHTML=overview(g);if(state.tab==='team')w.innerHTML=teamStats(g);if(state.tab==='players')w.innerHTML=playerBox(g);if(state.tab==='drives')w.innerHTML=driveChart(g);if(state.tab==='plays')w.innerHTML=plays(g);wirePlayerClicks()}
function overview(g){let a=team(g,'away').abbr,h=team(g,'home').abbr;let metrics=[['Total yards','Total Yards'],['Passing','Yards Passing'],['Rushing','Yards Rushing'],['First downs','First Downs'],['Turnovers','Turnovers'],['3rd down','Third Down Efficiency']];return `<div class="grid g3">${metrics.map(([l,k])=>`<div class="kpi"><small>${esc(l)}</small><strong>${esc(getStat(g,a,k))} <span class="muted">/</span> ${esc(getStat(g,h,k))}</strong><div class="muted">${esc(a)} / ${esc(h)}</div></div>`).join('')}</div><div class="grid g2" style="margin-top:14px"><div class="card"><div class="cardHead"><b>Game flow</b><span class="badge">FEED</span></div><div class="cardBody"><div class="chart">${scoreChart(g)}</div></div></div><div class="card"><div class="cardHead"><b>Scoring by quarter</b><span class="badge">FEED</span></div><div class="cardBody"><div class="chart">${quarterChart(g)}</div></div></div></div><div class="grid g2" style="margin-top:14px"><div class="card"><div class="cardHead"><b>Scoring summary</b></div><div class="cardBody feed">${(g.scoring_plays||[]).length?g.scoring_plays.map(x=>`<div class="feedItem"><small>Q${esc(x.period)} · ${esc(x.clock)}</small><b>${esc(x.team)} · ${esc(x.text)}</b></div>`).join(''):'<div class="empty">No scoring events yet.</div>'}</div></div><div class="card"><div class="cardHead"><b>Live leaders</b></div><div class="cardBody grid">${[pickLeader(g,['passingyards']),pickLeader(g,['rushingyards']),pickLeader(g,['receivingyards'])].map(leaderHtml).join('')}</div></div></div>`}
function teamStats(g){let ts=g.team_stats||{},teams=g.teams||[];let keys=[...new Set(Object.values(ts).flatMap(x=>Object.keys(x||{})))];return `<div class="card"><div class="cardBody tableWrap"><table class="dataTable"><thead><tr><th>Statistic</th>${teams.map(t=>`<th>${esc(t.abbr)}</th>`).join('')}</tr></thead><tbody>${keys.map(k=>`<tr><td>${esc(k)}</td>${teams.map(t=>`<td>${esc(ts[t.abbr]?.[k]??'—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`}
function playerBox(g){let ps=playerGroups(g);if(ps.length)return `<div class="card"><div class="cardHead"><b>Verified live box score</b><span class="badge">FEED</span></div><div class="cardBody"><div id="boxRows">${playerRows(ps)}</div></div></div>`;let roster=g?.roster_players||[];return `<div class="card"><div class="cardHead"><b>Pregame player board</b><span class="badge">BASELINE</span></div><div class="cardBody"><p class="muted">Live player statistics have not arrived yet. Showing the verified embedded matchup roster instead.</p>${baselineRows(roster)}</div></div>`}
function playerRows(ps){return ps.length?`<div class="tableWrap"><table class="dataTable"><thead><tr><th>Player</th><th>Team</th><th>Pos</th><th>Verified stat line</th></tr></thead><tbody>${ps.map(p=>`<tr><td><button class="linkBtn playerOpen" data-player="${esc(p.name)}">${esc(p.name)}</button></td><td>${esc(p.team)}</td><td>${esc(p.position)}</td><td>${Object.entries(p.stats).map(([k,v])=>`${esc(k)} ${esc(v)}`).join(' · ')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No player box-score data yet.</div>'}
function baselineRows(ps){return ps.length?`<div class="tableWrap"><table class="dataTable"><thead><tr><th>Player</th><th>Team</th><th>Pos</th><th>Unit</th><th>Verified baseline</th></tr></thead><tbody>${ps.map(p=>`<tr><td><button class="linkBtn baselineOpen" data-player="${esc(p.name)}">${esc(p.name)}</button></td><td>${esc(p.team)}</td><td>${esc(p.position)}</td><td>${esc(p.unit||'—')}</td><td>${esc(p.baseline||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No verified roster data is available for this matchup.</div>'}
function plays(g){return `<div class="card"><div class="cardBody feed">${(g.plays||[]).length?[...g.plays].reverse().map(p=>`<div class="feedItem"><small>Q${esc(p.period)} · ${esc(p.clock)} · ${esc(p.team)}</small><b>${esc(p.text)}</b></div>`).join(''):'<div class="empty">No play-by-play available yet.</div>'}</div></div>`}
function driveChart(g){return `<div class="card"><div class="cardHead"><b>Drive chart</b><span class="badge">FEED</span></div><div class="cardBody"><div class="field"></div><div style="margin-top:14px">${(g.drives||[]).length?g.drives.map((d,i)=>`<div class="feedItem"><small>Drive ${i+1} · ${esc(d.team)}</small><b>${esc(d.result)}</b><div class="driveBar" style="width:${Math.max(4,Math.min(100,Math.abs(num(d.yards)||8)))}%"></div><span class="muted">${esc(d.yards??'—')} yards · ${esc(d.plays??'—')} plays · ${esc(d.time??'—')}</span></div>`).join(''):'<div class="empty">No drive data yet.</div>'}</div></div></div>`}
function svgBase(content){return `<svg viewBox="0 0 700 240" role="img"><line x1="45" y1="205" x2="680" y2="205" stroke="#ffffff22"/><line x1="45" y1="20" x2="45" y2="205" stroke="#ffffff22"/>${content}</svg>`}
function scoreChart(g){let s=g.scoring_plays||[],a=team(g,'away'),h=team(g,'home');if(!s.length)return '<div class="empty">Scoring flow appears after the first score.</div>';let pts=[[0,0,0]],as=0,hs=0;s.forEach((x,i)=>{as=num(x.awayScore)??as;hs=num(x.homeScore)??hs;pts.push([i+1,as,hs])});let max=Math.max(7,...pts.flatMap(x=>x.slice(1))),X=i=>45+i*(635/(pts.length-1||1)),Y=v=>205-v*(175/max);let path=(idx,color)=>`<polyline fill="none" stroke="${color}" stroke-width="4" points="${pts.map((p,i)=>`${X(i)},${Y(p[idx])}`).join(' ')}"/>`;return svgBase(path(1,'#68d8ff')+path(2,'#c9ff3d'))+`<div class="legend"><span>${esc(a.abbr)} score</span><span>${esc(h.abbr)} score</span></div>`}
function quarterChart(g){let a=team(g,'away'),h=team(g,'home'),la=g.linescores?.[a.abbr]||[],lh=g.linescores?.[h.abbr]||[],n=Math.max(4,la.length,lh.length);let vals=[...Array(n)].map((_,i)=>[num(la[i])||0,num(lh[i])||0]);let max=Math.max(7,...vals.flat());let bars=vals.map((v,i)=>{let x=70+i*(580/n),w=Math.min(32,220/n),ha=v[0]*150/max,hh=v[1]*150/max;return `<rect x="${x}" y="${205-ha}" width="${w}" height="${ha}" rx="4" fill="#68d8ff"/><rect x="${x+w+5}" y="${205-hh}" width="${w}" height="${hh}" rx="4" fill="#c9ff3d"/><text x="${x}" y="225" fill="#8d98a5" font-size="11">Q${i+1}</text>`}).join('');return svgBase(bars)+`<div class="legend"><span>${esc(a.abbr)}</span><span>${esc(h.abbr)}</span></div>`}
function derived(g){let a=team(g,'away').abbr,h=team(g,'home').abbr;let rows=[];for(let ab of [a,h]){let plays=(g.plays||[]).filter(p=>p.team===ab),drives=(g.drives||[]).filter(d=>d.team===ab),score=num(team(g,team(g,'away').abbr===ab?'away':'home').score);let yards=num(getStat(g,ab,'Total Yards')),offplays=num(getStat(g,ab,'Total Plays','Offensive Plays'));rows.push({ab,plays:plays.length,drives:drives.length,ypp:yards!==null&&offplays?yards/offplays:null,ppd:score!==null&&drives.length?score/drives.length:null,explosive:plays.length?plays.filter(p=>{let st=p.start||{},en=p.end||{};let d=(num(en.yardLine)-num(st.yardLine));return Math.abs(d)>=20}).length/plays.length*100:null,threeOut:drives.length?drives.filter(d=>(num(d.plays)??99)<=3&&/punt/i.test(d.result||'')).length/drives.length*100:null})}return rows}
function renderAnalytics(){let g=state.game;if(!g){$('#analyticsBody').innerHTML='<div class="empty">Select a game in NFL Games first.</div>';return}let d=derived(g);$('#analyticsBody').innerHTML=`<div class="grid g4">${[['Yards / play','ypp'],['Points / drive','ppd'],['Explosive play rate','explosive'],['Three-and-out rate','threeOut']].map(([l,k])=>`<div class="kpi"><small>${esc(l)} <span class="badge derived">ƒ DERIVED</span></small><strong>${d.map(x=>x[k]===null?'—':x[k].toFixed(k.includes('rate')||k==='explosive'||k==='threeOut'?1:2)).join(' / ')}</strong><div class="muted">${d.map(x=>x.ab).join(' / ')}</div></div>`).join('')}</div><div class="grid g2" style="margin-top:14px"><div class="card"><div class="cardHead"><b>Game flow</b></div><div class="cardBody chart">${scoreChart(g)}</div></div><div class="card"><div class="cardHead"><b>Quarter scoring</b></div><div class="cardBody chart">${quarterChart(g)}</div></div></div><div class="card" style="margin-top:14px"><div class="cardHead"><b>Drive efficiency</b><span class="badge derived">ƒ DERIVED</span></div><div class="cardBody">${driveChart(g)}</div></div>`}
async function loadPlayerDb(){try{let d=await api('/api/players');state.players=d.players||[];let teams=[...new Set(state.players.map(x=>x.team).filter(Boolean))].sort(),pos=[...new Set(state.players.map(x=>x.position).filter(Boolean))].sort();$('#playerTeam').innerHTML='<option value="">All teams</option>'+teams.map(x=>`<option>${esc(x)}</option>`).join('');$('#playerPos').innerHTML='<option value="">All positions</option>'+pos.map(x=>`<option>${esc(x)}</option>`).join('');filterPlayers()}catch(e){$('#playerDb').innerHTML='<div class="empty">Player database unavailable.</div>'}}
function filterPlayers(){let q=$('#playerSearch').value.toLowerCase(),t=$('#playerTeam').value,p=$('#playerPos').value;let arr=state.players.filter(x=>(!q||x.name.toLowerCase().includes(q))&&(!t||x.team===t)&&(!p||x.position===p));$('#playerDb').innerHTML=arr.length?`<div class="tableWrap"><table class="dataTable"><thead><tr><th>Player</th><th>Team</th><th>Pos</th><th>Stored games</th></tr></thead><tbody>${arr.map(x=>`<tr><td><button class="linkBtn dbPlayer" data-name="${esc(x.name)}">${esc(x.name)}</button></td><td>${esc(x.team)}</td><td>${esc(x.position)}</td><td>${x.games?.length||0}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No matching players.</div>';$$('.dbPlayer').forEach(b=>b.onclick=()=>showProfile(state.players.find(x=>x.name===b.dataset.name)))}
$('#playerSearch').oninput=filterPlayers;$('#playerTeam').onchange=filterPlayers;$('#playerPos').onchange=filterPlayers;
function showProfile(p){if(!p)return;let games=p.games||[];$('#playerProfile').innerHTML=`<div class="card"><div class="cardBody profile"><img class="profilePortrait" src="${playerImg(p)}" onerror="this.style.display='none'"><div><div class="eyebrow">${esc(p.team)} · ${esc(p.position)}</div><h2 class="title" style="font-size:38px">${esc(p.name)}</h2>${p.baseline?`<div class="kpi" style="margin-bottom:12px"><small>Verified baseline</small><strong style="font-size:15px">${esc(p.baseline)}</strong></div>`:''}<div class="grid g3">${games.slice(-6).map(g=>`<div class="kpi"><small>${esc(g.status)}</small><strong style="font-size:15px">${Object.entries(g.stats||{}).slice(0,4).map(([k,v])=>`${esc(k)} ${esc(v)}`).join(' · ')||'—'}</strong></div>`).join('')}</div></div></div></div>`}
function wirePlayerClicks(){$$('.playerOpen').forEach(b=>b.onclick=()=>{let p=playerGroups(state.game).find(x=>x.name===b.dataset.player);route({view:'players'});setTimeout(()=>showProfile(p),100)});$$('.baselineOpen').forEach(b=>b.onclick=()=>{let p=(state.game?.roster_players||[]).find(x=>x.name===b.dataset.player);route({view:'players'});setTimeout(()=>showProfile({...p,games:[]}),100)})}
async function loadArchive(){try{let d=await api('/api/archive');let gs=d.games||[];$('#archiveList').innerHTML=gs.length?gs.map(g=>`<button class="gameCard archiveOpen" data-id="${esc(g.id)}"><div class="gameTeams">${esc((g.teams||[]).map(t=>t.abbr+' '+t.score).join(' · '))}</div><div class="gameMeta">${esc(g.status)} · ${esc(g.id)}</div></button>`).join(''):'<div class="empty">No archived games yet.</div>';$$('.archiveOpen').forEach(b=>b.onclick=()=>openArchive(b.dataset.id))}catch(e){$('#archiveList').innerHTML='<div class="empty">Archive unavailable.</div>'}}
async function openArchive(id){let [g,h]=await Promise.all([api('/api/game?id='+encodeURIComponent(id)),api('/api/history?id='+encodeURIComponent(id))]);$('#archiveReplay').innerHTML=`<div class="hero">${hero(g)}</div><div class="grid g2" style="margin-top:14px"><div class="card"><div class="cardHead"><b>Final team stats</b></div><div class="cardBody">${teamStats(g)}</div></div><div class="card"><div class="cardHead"><b>Saved progression</b></div><div class="cardBody feed">${(h.snapshots||[]).map(x=>`<div class="feedItem"><small>${new Date(x.t*1000).toLocaleTimeString()}</small><b>${Object.entries(x.scores||{}).map(([k,v])=>`${esc(k)} ${esc(v)}`).join(' · ')}</b></div>`).join('')||'<div class="empty">No snapshots.</div>'}</div></div></div>`}
async function health(){try{let h=await api('/api/health');if(!state.lastSync)$('#healthText').textContent=`${h.provider} · ${h.database}`;$('#setProvider').textContent=h.provider;$('#setDb').textContent=h.database;$('#setCollector').textContent=`${h.collector_seconds}s cadence`;$('#setLast').textContent=h.last?.collector?new Date(h.last.collector*1000).toLocaleTimeString():'—'}catch(e){$('#healthText').textContent='CONNECTION DEGRADED'}}
function renderSyncStatus(){const el=document.getElementById('healthText');if(!el)return;const age=state.lastSync?Math.max(0,Math.round((Date.now()-state.lastSync)/1000)):null;const phase=state.game?.state==='in'?'LIVE':(state.game?.completed||state.game?.state==='post'?'FINAL':'PREGAME');if(state.syncFailures)el.textContent=`SYNC RETRYING · ${state.syncFailures} failed`;else if(age!==null)el.textContent=`${phase} · synced ${age}s ago`; }
function startPolling(){clearInterval(state.timer);if(!state.gameId)return;const tick=()=>loadSelected(state.gameId,{restart:false});state.timer=setInterval(tick,Math.max(3000,state.refresh));}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.gameId)loadSelected(state.gameId)});window.addEventListener('focus',()=>{if(state.gameId)loadSelected(state.gameId)});
document.addEventListener('keydown',e=>{if(e.altKey&&e.key==='ArrowLeft'){e.preventDefault();history.back()}if(e.altKey&&e.key.toLowerCase()==='g'){e.preventDefault();route({view:'games'})}});
function initialRoute(){let parts=location.hash.replace(/^#/,'').split('/').filter(Boolean);let views=new Set(['home','games','players','analytics','archive']);let tabs=new Set(['overview','team','players','plays','drives']);return {view:views.has(parts[0])?parts[0]:'home',tab:tabs.has(parts[1])?parts[1]:'overview',gameId:parts[2]||null,date:state.date,scrollY:0}}
(async function init(){let initial=initialRoute();Object.assign(state,initial);history.replaceState(initial,'',`#${initial.view}/${initial.tab}${initial.gameId?'/'+initial.gameId:''}`);renderRoute();health();try{let d=await api('/api/games?date='+state.date);state.games=d.games||[];let first=state.games.find(x=>x.state==='in')||state.games[0];if(first)await loadSelected(first.id)}catch(e){}renderHome();setInterval(health,30000)})();
