let deferredPrompt=null;
const btn=document.getElementById('install');
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;btn.hidden=false});
btn.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;btn.hidden=true});
window.addEventListener('appinstalled',()=>{btn.hidden=true});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
document.addEventListener("DOMContentLoaded",()=>{let host=document.querySelector("main")||document.body;if(!document.getElementById("atlasUniversal")){let s=document.createElement("section");s.id="atlasUniversal";s.className="universal";s.innerHTML=`<span>ATLAS UNIVERSAL SEARCH</span><div><input id="uq" placeholder="Search MLB or UFC…"><button id="ub">SEARCH</button></div><small>Search MLB players/teams and UFC fighters. NFL search remains inside NFL ATLAS.</small><div id="ur"></div>`;host.appendChild(s);let run=async()=>{let q=document.getElementById("uq").value.trim();if(q.length<2)return;let o=document.getElementById("ur");o.textContent="Searching…";try{let [mr,ur]=await Promise.all([fetch("/api/mlb/search?q="+encodeURIComponent(q)),fetch("/api/ufc/search?q="+encodeURIComponent(q))]);let m=await mr.json(),u=await ur.json();let rows=[...(m.results||[]).slice(0,5).map(v=>({href:"/mlb/#players",name:v.name,detail:(v.detail||"")+" · MLB"})),...(u.results||[]).slice(0,5).map(v=>({href:"/ufc/#fighters",name:v.name,detail:(v.nickname||v.weight||"")+" · UFC"}))];o.innerHTML=rows.map(v=>`<a href="${v.href}">${v.name}<small>${v.detail}</small></a>`).join("")||"No matches."}catch(e){o.textContent="Search unavailable."}};document.getElementById("ub").onclick=run;document.getElementById("uq").onkeydown=e=>{if(e.key==="Enter")run()}}});

document.addEventListener("DOMContentLoaded",async()=>{try{let x=await ATLAS52.getJSON("/api/system-health",{ttl:30000});let host=document.querySelector(".universal")||document.querySelector("main")||document.body;let n=document.createElement("div");n.className="system53";n.innerHTML=`<span class="data-quality ${x.ok?"":"warn"}"><i></i>ATLAS SYSTEM ${x.ok?"HEALTHY":"CHECK"}</span><small>NFL ${x.components?.nfl_store?.ok?"✓":"!"} · MLB ${x.components?.mlb_store?.ok?"✓":"!"} · UFC ${x.components?.ufc_cache?.ok?"✓":"!"}</small>`;host.appendChild(n)}catch{}})

document.addEventListener("DOMContentLoaded",async()=>{let q=document.querySelector(".universal");if(!q||document.getElementById("homebase54"))return;let h=document.createElement("section");h.id="homebase54";h.className="homebase54";h.innerHTML=`<div class="homehero54"><span>ATLAS HOMEBASE 2.0</span><h2>YOUR SPORTS.<br>ONE COMMAND CENTER.</h2><p>Live entry points, archive health and event intelligence across ATLAS.</p></div><div class="homegrid54"><section class="homecard54 wide"><h3>TODAY / NEXT UP</h3><div id="hbnext"><div class="skeleton"></div></div></section><section class="homecard54"><h3>PLATFORM STATUS</h3><div id="hbstatus"><div class="skeleton"></div></div></section><section class="homecard54 full"><h3>COMMAND CENTERS</h3><div class="sportstatus54"><a href="/nfl/"><b>NFL ATLAS</b><span>GAME + TEAM INTELLIGENCE →</span></a><a href="/mlb/"><b>MLB ATLAS</b><span>GAMECAST + ARCHIVE →</span></a><a href="/ufc/"><b>UFC ATLAS</b><span>FIGHTER + ROUND INTELLIGENCE →</span></a></div></section></div>`;q.insertAdjacentElement("afterend",h);try{let x=await ATLAS52.getJSON("/api/homebase",{ttl:20000}),rows=[];(x.mlb?.games||[]).slice(0,4).forEach(g=>rows.push(`<a class="jump54" href="/mlb/"><span><b>${g.away?.name||g.away||"Away"} vs ${g.home?.name||g.home||"Home"}</b><small>MLB · ${g.status||g.datetime||"Scheduled"}</small></span><i>→</i></a>`));(x.ufc?.events||[]).slice(0,3).forEach(e=>rows.push(`<a class="jump54" href="/ufc/"><span><b>${e.name}</b><small>UFC · ${e.date||""}</small></span><i>→</i></a>`));document.getElementById("hbnext").innerHTML=rows.join("")||'<div class="empty">No current event rows.</div>';let c=x.system?.components||{};document.getElementById("hbstatus").innerHTML=`<div class="livebar54"><span>NFL DATA</span><b>${c.nfl_store?.ok?"HEALTHY":"CHECK"}</b></div><div class="livebar54"><span>MLB ARCHIVE</span><b>${c.mlb_store?.games??0} GAMES</b></div><div class="livebar54"><span>UFC</span><b>${c.ufc_cache?.ok?"READY":"CHECK"}</b></div><div class="livebar54"><span>AI</span><b>${c.gemini?.configured?"READY":"OPTIONAL"}</b></div>`}catch(e){document.getElementById("hbnext").innerHTML='<div class="empty">Homebase data temporarily unavailable.</div>'}});
document.addEventListener("DOMContentLoaded",async()=>{let g=document.querySelector(".homegrid54");if(!g||document.getElementById("intelfeed60"))return;let s=document.createElement("section");s.className="homecard54 full";s.id="intelfeed60";s.innerHTML='<h3>ATLAS INTELLIGENCE FEED</h3><div class="intelfeed60"><div class="skeleton"></div></div>';g.appendChild(s);try{let x=await ATLAS52.getJSON("/api/intelligence-feed",{ttl:30000});s.querySelector(".intelfeed60").innerHTML=(x.items||[]).map(i=>`<article class="intelitem60"><span>${i.sport}</span><b>${i.title}</b><p>${i.detail||""}</p>${ATLAS60.receipt("EVIDENCE",i.receipt||[])}<button class="ask60 ask61" data-atlas-prompt="Explain this ${i.sport} ATLAS signal using only verified ATLAS evidence: ${i.title} — ${i.detail||""}">EXPLAIN THIS</button></article>`).join("")||'<div class="empty">Intelligence builds from verified stored data.</div>'}catch(e){s.querySelector(".intelfeed60").innerHTML='<div class="empty">Intelligence feed temporarily unavailable.</div>'}});
document.addEventListener("DOMContentLoaded",async()=>{try{let x=await ATLAS52.getJSON("/api/integrity",{ttl:30000});let s=document.querySelector("#hbstatus");if(s){let d=document.createElement("div");d.className="livebar54";d.innerHTML=`<span>INTEGRITY</span><b>${x.ok?"PASS":"CHECK"}</b>`;s.appendChild(d)}}catch{}});
