function mlbBroadcast60(g){let o=g?.offense||g?.linescore?.offense||g?.liveData?.linescore?.offense||{},b={1:!!(o.first||o.firstBase),2:!!(o.second||o.secondBase),3:!!(o.third||o.thirdBase)},ev=(g?.recent_plays||g?.plays||[]).map(p=>({inning:p.inning||p.about?.inning||"",text:p.description||p.result?.description||""})).filter(x=>x.text);return `<div class="broadcast60"><section>${ATLAS60.diamond(b)}</section><section><h3>PLAY TIMELINE</h3>${ATLAS60.eventTimeline(ev)}<button class="ask60 ask61" data-atlas-prompt="Explain this MLB game state using only verified ATLAS data.">EXPLAIN GAME</button></section></div>`}

function atlasLineChart(rows,xKey,yKey,label){
 rows=(rows||[]).map(r=>({x:r?.[xKey],y:Number(r?.[yKey])})).filter(r=>r.x!=null&&Number.isFinite(r.y));
 if(rows.length<2)return `<div class="empty">More verified data is needed for this trend.</div>`;
 let W=760,H=230,P=28,ys=rows.map(r=>r.y),mn=Math.min(...ys),mx=Math.max(...ys);if(mx===mn){mx+=1;mn-=1}
 let X=i=>P+i*(W-P*2)/Math.max(1,rows.length-1),Y=v=>H-P-(v-mn)*(H-P*2)/(mx-mn);
 let pts=rows.map((r,i)=>`${X(i)},${Y(r.y)}`).join(" "),area=`${P},${H-P} ${pts} ${W-P},${H-P}`;
 let grid=[0,.25,.5,.75,1].map(t=>`<line class="gridline" x1="${P}" x2="${W-P}" y1="${P+t*(H-P*2)}" y2="${P+t*(H-P*2)}"/>`).join("");
 let dots=rows.map((r,i)=>`<circle class="dot" cx="${X(i)}" cy="${Y(r.y)}" r="4"><title>${String(r.x)} · ${r.y}</title></circle>`).join("");
 return `<div class="chart-title"><b>${label}</b><span>${rows.length} VERIFIED POINTS</span></div><svg class="atlas-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="${label}">${grid}<polygon class="area" points="${area}"/><polyline class="line" points="${pts}"/>${dots}<text class="axis" x="${P}" y="${H-5}">${String(rows[0].x)}</text><text class="axis" text-anchor="end" x="${W-P}" y="${H-5}">${String(rows[rows.length-1].x)}</text></svg>`}

const $=s=>document.querySelector(s),V=$("#view"),pages=[["home","Home","⌂"],["games","Games","⚾"],["teams","Teams","◆"],["players","Players","◉"],["standings","Standings","▥"],["leaders","Leaders","★"],["analytics","Analytics Lab","⌁"],["compare","Compare Lab","⇄"],["graphs","GameCast","◇"],["daily","ATLAS Daily","▤"],["recap","Weekly Recap","▦"],["ai","ATLAS AI","A"]];
let state={page:"home",games:[],teams:[],standings:[],leaders:{},game:null,team:null,player:null,power:[],daily:null,compare:[]};
const esc=x=>String(x??"—").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const api=async u=>{let r=await fetch(u,{cache:"no-store"}),x=await r.json();if(!r.ok||x?.ok===false)throw new Error(x?.error||("Request failed "+r.status));return x};
$("#nav").innerHTML=pages.map(([id,n,ic])=>`<button data-page="${id}" data-icon="${ic}">${n}</button>`).join("");
$("#nav").onclick=e=>{let b=e.target.closest("button");if(b){state.page=b.dataset.page;render()}};
setInterval(()=>$("#clock").textContent=new Date().toLocaleString(),1000);
function shell(name,body){$("#title").textContent=name.toUpperCase();document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===state.page));V.innerHTML=`<div class="page">${body}</div>`}
const gameRows=gs=>gs.length?gs.map(g=>`<div class="game" onclick="openGame('${g.id}')"><div class="team"><b>${esc(g.away?.name)}</b><div class="muted">${esc(g.away?.probable||"")}</div></div><div><div class="score">${esc(g.away?.score??"—")} · ${esc(g.home?.score??"—")}</div><span class="tag">${esc(g.inningState&&g.inning?g.inningState+" "+g.inning:g.status)}</span></div><div class="team"><b>${esc(g.home?.name)}</b><div class="muted">${esc(g.home?.probable||"")}</div></div></div>`).join(""):`<div class="empty">No MLB games returned for this date.</div>`;
async function ensure(){if(!state.games.length){let [g,t,s,l]=await Promise.all([api("/api/mlb/schedule"),api("/api/mlb/teams"),api("/api/mlb/standings"),api("/api/mlb/leaders")]);state.games=g.games||[];state.teams=t.teams||[];state.standings=s.standings||[];state.leaders=l.leaders||{}}}
async function render(){shell(state.page,`<div class="loading">LOADING VERIFIED MLB DATA…</div>`);try{await ensure(); if(state.page==="home")home();if(state.page==="games")games();if(state.page==="teams")teams();if(state.page==="players")playersPage();if(state.page==="standings")standingsPage();if(state.page==="leaders")leadersPage();if(state.page==="analytics")analyticsPage();if(state.page==="compare")comparePage();if(state.page==="graphs")graphs();if(state.page==="daily")dailyPage();if(state.page==="recap")recap();if(state.page==="ai")ai()}catch(e){shell(state.page,`<div class="empty">MLB data could not load right now.<br>${esc(e.message)}</div>`)}}
function home(){let live=state.games.filter(g=>g.abstract==="Live"),finals=state.games.filter(g=>g.abstract==="Final");shell("Home",`<div class="hero"><div><span class="ey">MLB ATLAS / BASEBALL COMMAND</span><h1>BASEBALL<br><em>COMMAND.</em></h1><p>Verified MLB game data, standings, teams and live game state.</p></div><span class="tag">${live.length} LIVE</span></div><div class="grid"><section class="card wide"><h3>TODAY'S GAMES</h3>${gameRows(state.games)}</section><section class="card"><h3>LEAGUE PULSE</h3><div class="statgrid"><div class="stat"><span>GAMES</span><b>${state.games.length}</b></div><div class="stat"><span>LIVE</span><b>${live.length}</b></div><div class="stat"><span>FINAL</span><b>${finals.length}</b></div><div class="stat"><span>TEAMS</span><b>${state.teams.length}</b></div></div><p class="muted">Source: MLB Stats API. Missing values stay missing.</p></section><section class="card full"><h3>DIVISION STANDINGS</h3>${standingsTable(state.standings)}</section><section class="card full"><h3>MLB LEADERS</h3>${leaderStrip()}</section></div>`)}
function games(){shell("Games",`<div class="hero"><div><span class="ey">SCOREBOARD</span><h1>MLB <em>GAMES.</em></h1></div><input id="date" class="select" type="date"></div><div class="card full" id="gamesList">${gameRows(state.games)}</div>`);$("#date").onchange=async e=>{let x=await api("/api/mlb/schedule?date="+e.target.value);state.games=x.games||[];$("#gamesList").innerHTML=gameRows(state.games)}}
async function openGame(id){state.game=await api("/api/mlb/game?id="+id);state.page="graphs";graphs();startGameCast()}let gameTimer=null;function startGameCast(){clearInterval(gameTimer);if(state.game&&/live|progress/i.test(state.game.status||""))gameTimer=setInterval(async()=>{if(state.page!=="graphs"){clearInterval(gameTimer);return}try{state.game=await api("/api/mlb/game?id="+state.game.id);graphs()}catch{}},8000)}
function diamond(g){let b=g?.bases||{};return `<div class="diamond"><div class="field"></div><i class="base b1 ${b.first?"on":""}"></i><i class="base b2 ${b.second?"on":""}"></i><i class="base b3 ${b.third?"on":""}"></i><i class="base home"></i></div><div class="count"><b>${esc(g?.inningState)} ${esc(g?.inningOrdinal||g?.inning)}</b><br>B ${esc(g?.balls)} · S ${esc(g?.strikes)} · O ${esc(g?.outs)}</div>`}
function graphs(){let g=state.game;if(!g){shell("Game Graphs",`<div class="hero"><div><span class="ey">DIAMOND COMMAND CENTER</span><h1>GAME <em>GRAPHS.</em></h1><p>Select a game to open the live baseball command center.</p></div></div><div class="card full">${gameRows(state.games)}</div>`);return}let inn=g.innings||[];shell("Game Graphs",`<div class="hero"><div><span class="ey">GAME ${esc(g.id)} / ${esc(g.status)}</span><h1>${esc(g.away?.abbr)} ${esc(g.away?.runs)} <em>—</em> ${esc(g.home?.runs)} ${esc(g.home?.abbr)}</h1><p>${esc(g.venue)}</p></div><button class="action" onclick="refreshGame()">REFRESH</button></div><div class="grid"><section class="card">${diamond(g)}<p class="muted">At bat: ${esc(g.batter)}<br>Pitching: ${esc(g.pitcher)}</p></section><section class="card wide"><h3>LINE SCORE</h3><table class="lines"><tr><th>TEAM</th>${inn.map(x=>`<th>${esc(x.num)}</th>`).join("")}<th>R</th><th>H</th><th>E</th></tr><tr><td>${esc(g.away?.abbr)}</td>${inn.map(x=>`<td>${esc(x.away?.runs??"")}</td>`).join("")}<td>${esc(g.away?.runs)}</td><td>${esc(g.away?.hits)}</td><td>${esc(g.away?.errors)}</td></tr><tr><td>${esc(g.home?.abbr)}</td>${inn.map(x=>`<td>${esc(x.home?.runs??"")}</td>`).join("")}<td>${esc(g.home?.runs)}</td><td>${esc(g.home?.hits)}</td><td>${esc(g.home?.errors)}</td></tr></table></section><section class="card half"><h3>RECENT PLAYS</h3>${(g.plays||[]).slice(-10).reverse().map(p=>`<div class="play"><b>${esc(p.half)} ${esc(p.inning)} · ${esc(p.event)}</b><br>${esc(p.description)}</div>`).join("")||'<div class="empty">No captured plays.</div>'}</section><section class="card half"><h3>PLAYER LINES</h3>${playerLines(g)}</section><section class="card full"><h3>CINEMATIC INNING FLOW</h3>${inningCinema53(g)}</section><section class="card full"><h3>RUN FLOW BY INNING</h3>${inningFlow(g)}</section><section class="card half"><h3>BATTING BOARD</h3>${battingBoard(g)}</section><section class="card half"><h3>PITCHING BOARD</h3>${pitchingBoard(g)}</section></div>`)}


function gamePeople(g,kind){let direct=kind==="hit"?(g.hitters||[]):(g.pitchers||[]);if(direct.length)return direct;
 let out=[],bs=g.boxscore||g.liveData?.boxscore||{},teams=bs.teams||{};
 for(let side of ["away","home"]){let T=teams[side]||{},players=T.players||{};for(let p of Object.values(players)){let st=p.stats||{},group=kind==="hit"?(st.batting||{}):(st.pitching||{});if(Object.keys(group).length)out.push({id:p.person?.id,name:p.person?.fullName||p.person?.name||"Player",team:T.team?.abbreviation||T.team?.name||side,stats:group})}}
 return out}

function inningFlow(g){let rawInnings=g.innings||g.linescore?.innings||g.liveData?.linescore?.innings||[];let rows=rawInnings.map(x=>({n:x.num||x.ordinalNum||x.inningNum,a:num(x.away?.runs)||0,h:num(x.home?.runs)||0})),mx=Math.max(1,...rows.flatMap(x=>[x.a,x.h]));return rows.length?`<div class="inningsViz">${rows.map(x=>`<div class="inningCol"><div class="ibars"><i class="awaybar" style="height:${Math.max(4,x.a/mx*100)}%"></i><i class="homebar" style="height:${Math.max(4,x.h/mx*100)}%"></i></div><b>${esc(x.n)}</b><small>${x.a}-${x.h}</small></div>`).join("")}</div><div class="legend"><span>AWAY</span><span>HOME</span></div>`:'<div class="empty">Run flow appears when inning data is available.</div>'}
function battingBoard(g){return gamePeople(g,"hit").filter(x=>x.stats?.atBats!=null).slice(0,18).map(x=>`<div class="rank clickable" onclick="openPlayer('${x.id}')"><span><b>${esc(x.name)}</b><small>${esc(x.team)}</small></span><em>${esc(x.stats.hits)}-${esc(x.stats.atBats)} · ${esc(x.stats.homeRuns)} HR · ${esc(x.stats.rbi)} RBI</em></div>`).join("")||'<div class="empty">No verified batting lines yet.</div>'}
function pitchingBoard(g){return gamePeople(g,"pitch").filter(x=>x.stats?.inningsPitched!=null).slice(0,14).map(x=>`<div class="rank clickable" onclick="openPlayer('${x.id}')"><span><b>${esc(x.name)}</b><small>${esc(x.team)}</small></span><em>${esc(x.stats.inningsPitched)} IP · ${esc(x.stats.strikeOuts)} K · ${esc(x.stats.earnedRuns)} ER</em></div>`).join("")||'<div class="empty">No verified pitching lines yet.</div>'}

async function refreshGame(){if(state.game){state.game=await api("/api/mlb/game?id="+state.game.id);graphs()}}
function playerLines(g){let h=gamePeople(g,"hit").filter(x=>x.stats?.atBats||x.stats?.hits).slice(0,12);return h.map(x=>`<div class="play"><b>${esc(x.name)} · ${esc(x.team)}</b><br>${esc(x.stats.hits)} H · ${esc(x.stats.atBats)} AB · ${esc(x.stats.runs)} R · ${esc(x.stats.rbi)} RBI · ${esc(x.stats.homeRuns)} HR</div>`).join("")||'<div class="empty">No verified batting lines yet.</div>'}
function standingsTable(r){return `<table class="lines"><tr><th>TEAM</th><th>W</th><th>L</th><th>PCT</th><th>GB</th><th>STRK</th></tr>${r.map(x=>`<tr><td>${esc(x.team)}</td><td>${esc(x.wins)}</td><td>${esc(x.losses)}</td><td>${esc(x.pct)}</td><td>${esc(x.gb)}</td><td>${esc(x.streak)}</td></tr>`).join("")}</table>`}

function num(v){let n=Number(v);return Number.isFinite(n)?n:null}
function neonBars(rows,labelKey,valueKey,title,suffix=""){let clean=(rows||[]).map(x=>({label:x[labelKey],v:num(x[valueKey])})).filter(x=>x.v!=null).slice(0,15),mx=Math.max(1,...clean.map(x=>x.v));return `<div class="viz"><h3>${title}</h3>${clean.length?clean.map(x=>`<div class="vrow"><span>${esc(x.label)}</span><div class="track"><i style="width:${Math.max(2,x.v/mx*100)}%"></i></div><b>${esc(x.v)}${suffix}</b></div>`).join(""):`<div class="empty">Not enough verified data to draw this graph.</div>`}</div>`}
function standingsPage(){let divs={};state.standings.forEach(x=>(divs[x.division||"MLB"]??=[]).push(x));shell("Standings",`<div class="hero"><div><span class="ey">LEAGUE TABLE</span><h1>MLB <em>STANDINGS.</em></h1><p>American and National League division races from verified MLB standings.</p></div></div><div class="grid">${Object.entries(divs).map(([d,r])=>`<section class="card half"><h3>${esc(d)}</h3>${standingsTable(r)}</section>`).join("")}<section class="card full">${neonBars([...state.standings].sort((a,b)=>Number(b.pct)-Number(a.pct)).slice(0,15),"team","pct","WINNING PERCENTAGE — TOP 15")}</section></div>`)}

function leaderRows(k){let L=state.leaders||{},aliases={
 homeRuns:["homeRuns","home_runs"],battingAverage:["battingAverage","avg","batting_average"],
 runsBattedIn:["runsBattedIn","rbi","runs_batted_in"],stolenBases:["stolenBases","stolen_bases"],
 hits:["hits"],earnedRunAverage:["earnedRunAverage","era","earned_run_average"],
 strikeouts:["strikeouts","strikeOuts"],wins:["wins"],saves:["saves"]
};for(let a of (aliases[k]||[k]))if(Array.isArray(L[a]))return L[a];return []}

function leadersPage(){let cats=[["homeRuns","HOME RUNS"],["battingAverage","BATTING AVG"],["runsBattedIn","RBI"],["stolenBases","STOLEN BASES"],["hits","HITS"],["earnedRunAverage","ERA"],["strikeouts","STRIKEOUTS"],["wins","PITCHER WINS"],["saves","SAVES"]];shell("Leaders",`<div class="hero"><div><span class="ey">PLAYER COMMAND</span><h1>MLB <em>LEADERS.</em></h1><p>Dedicated hitting and pitching leaderboards. Click a player for the full ATLAS profile.</p></div></div><div class="grid">${cats.map(([k,n])=>`<section class="card third"><h3>${n}</h3>${leaderRows(k).slice(0,10).map(x=>`<div class="rank clickable" onclick="openPlayer('${x.playerId}')"><strong>${esc(x.rank)}</strong><span><b>${esc(x.player)}</b><small>${esc(x.team)}</small></span><em>${esc(x.value)}</em></div>`).join("")||'<div class="empty">No verified leaders returned.</div>'}</section>`).join("")}</div>`)}



function inningCinema53(g){let ins=g?.innings||g?.linescore?.innings||g?.liveData?.linescore?.innings||[];let rows=ins.map((x,i)=>({name:String(x.ordinalNum||x.num||x.inningNum||i+1),away:Number(x.away?.runs??x.away??0),home:Number(x.home?.runs??x.home??0)}));if(!rows.length)return '<div class="empty">Inning visualization appears when verified line-score data arrives.</div>';let max=Math.max(1,...rows.flatMap(x=>[x.away,x.home]));return `<div class="inningcinema53">${rows.map(x=>`<div class="inning53"><b>${esc(x.name)}</b><div class="runlane away"><i style="height:${Math.max(4,x.away/max*100)}%"></i><span>${x.away}</span></div><div class="runlane home"><i style="height:${Math.max(4,x.home/max*100)}%"></i><span>${x.home}</span></div></div>`).join("")}</div><div class="inninglegend53"><span>AWAY</span><span>HOME</span></div>`}
function archiveMomentum53(a){let gs=(a?.games||[]).slice().reverse();return ATLAS53.spark(gs.map(g=>Number(g.payload?.home?.runs||0)+Number(g.payload?.away?.runs||0)),{label:"ARCHIVED GAME RUN ENVIRONMENT"})}

function dataQuality52(label,count){let n=Number(count||0),cls=n>10?"":n?"warn":"bad";return `<span class="data-quality ${cls}"><i></i>${label}: ${n?`${n} VERIFIED`:"BUILDING"}</span>`}
function refreshStamp52(){return `<span class="freshness">UPDATED ${new Date().toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</span>`}
async function playersPage(){shell("Players",`<div class="hero"><div><span class="ey">UNIVERSAL MLB SEARCH</span><h1>PLAYER <em>HUBS.</em></h1><p>Search active MLB rosters and open a full player intelligence profile.</p></div></div><section class="card full"><input id="psearch" class="searchbox" placeholder="Search player or team…" autocomplete="off"><div id="searchout" class="searchout"></div></section>`);let box=$("#psearch"),out=$("#searchout"),timer;box.oninput=()=>{clearTimeout(timer);timer=setTimeout(async()=>{if(box.value.trim().length<2){out.innerHTML="";return}let r=await api("/api/mlb/search?q="+encodeURIComponent(box.value));out.innerHTML=(r.results||[]).map(x=>`<button class="searchhit" onclick="${x.type==="player"?`openPlayer('${x.id}')`:`openTeam('${x.id}')`}"><b>${esc(x.name)}</b><span>${esc(x.detail)} · ${esc(x.type)}</span></button>`).join("")||'<div class="empty">No matches.</div>'},280)}}
async function openTeam(id){state.page="teams";teams();setTimeout(()=>{let s=$("#teamSel");if(s){s.value=String(id);s.dispatchEvent(new Event("change"))}},0)}
async function analyticsPage(){shell("Analytics Lab",`<div class="loading">BUILDING ATLAS BASEBALL INTELLIGENCE…</div>`);let [p,a]=await Promise.all([api("/api/mlb/power"),api("/api/mlb/archive")]);state.power=p.teams||[];let top=state.power.slice(0,15);shell("Analytics Lab",`<div class="hero"><div><span class="ey">ATLAS MODEL / VERIFIED ARCHIVE</span><h1>ANALYTICS <em>LAB.</em></h1><p>Season record blended with archived recent form and run differential. ATLAS model output — not an official MLB ranking.</p></div><div>${dataQuality52("ARCHIVE",a.counts?.games)}${refreshStamp52()}</div></div><div class="grid"><section class="card wide">${neonBars(top,"team","strength","ATLAS TEAM STRENGTH")}</section><section class="card"><h3>ARCHIVE HEALTH</h3><div class="statgrid">${["games","team_rows","player_rows"].map(k=>`<div class="stat"><span>${k.replace("_"," ").toUpperCase()}</span><b>${esc(a.counts?.[k])}</b></div>`).join("")}</div><button class="action" onclick="backfillMLB()">SYNC LAST 7 DAYS</button></section><section class="card full"><h3>ARCHIVE MOMENTUM</h3>${archiveMomentum53(a)}</section><section class="card full"><h3>POWER TABLE</h3><table class="lines"><tr><th>#</th><th>TEAM</th><th>RECORD</th><th>ATLAS</th><th>RECENT</th><th>RUN DIFF</th></tr>${top.map(x=>`<tr><td>${x.rank}</td><td>${esc(x.team)}</td><td>${esc(x.record)}</td><td>${esc(x.strength)}</td><td>${esc(x.recent_wins)}-${Math.max(0,x.recent_games-x.recent_wins)}</td><td>${esc(x.run_diff_recent)}</td></tr>`).join("")}</table></section></div>`)}
async function backfillMLB(){let b=document.querySelector(".action");if(b)b.textContent="SYNCING…";let r=await api("/api/mlb/backfill?days=7&limit=40");ATLAS52.clear("/api/mlb/");ATLAS52.toast(`Archived ${r.hydrated} completed games · ${r.counts?.games||0} total`,"good");analyticsPage()}
function comparePage(){shell("Compare Lab",`<div class="hero"><div><span class="ey">PLAYER VS PLAYER</span><h1>COMPARE <em>LAB.</em></h1><p>Add up to four MLB players from search, then compare their verified season production.</p></div></div><section class="card full"><input id="cmpsearch" class="searchbox" placeholder="Search a player to add…"><div id="cmpresults"></div></section><div id="cmpboard" class="comparegrid">${compareCards()}</div>`);let q=$("#cmpsearch"),o=$("#cmpresults"),timer;q.oninput=()=>{clearTimeout(timer);timer=setTimeout(async()=>{if(q.value.trim().length<2){o.innerHTML="";return}let r=await api("/api/mlb/search?q="+encodeURIComponent(q.value));o.innerHTML=(r.results||[]).filter(x=>x.type==="player").slice(0,8).map(x=>`<button class="searchhit" onclick="addCompare('${x.id}')"><b>${esc(x.name)}</b><span>${esc(x.detail)}</span></button>`).join("")},250)}}
async function addCompare(id){if(state.compare.some(x=>String(x.id)===String(id))||state.compare.length>=4)return;let r=await api("/api/mlb/player?id="+id);if(r.player)state.compare.push(r.player);comparePage()}
function compareCards(){return state.compare.length?state.compare.map((p,i)=>{let st=p.stats||{},x=st.hitting||st.pitching||{};return `<section class="card comparecard"><button class="close mini" onclick="state.compare.splice(${i},1);comparePage()">×</button><span class="ey">${esc(p.position)}</span><h2>${esc(p.name)}</h2><p>${esc(p.team)}</p><div class="statgrid">${statsCards(x,Object.keys(st.hitting||{}).length?["gamesPlayed","runs","hits","homeRuns","rbi","stolenBases","avg","obp","slg","ops"]:["gamesPlayed","wins","losses","era","inningsPitched","strikeOuts","whip","saves"])}</div></section>`}).join(""):'<section class="card full empty">Search and add players to begin comparing.</section>'}
async function dailyPage(){shell("ATLAS Daily",`<div class="loading">PRINTING TODAY'S ATLAS DAILY…</div>`);let d=await api("/api/mlb/daily");state.daily=d;shell("ATLAS Daily",`<div class="newspaper"><span class="ey">${esc(d.date)} · VERIFIED BASEBALL BRIEF</span><h1>ATLAS <em>DAILY.</em></h1><p class="dek">Today's games, league leaders, ATLAS power signals and archive status in one baseball briefing.</p></div><div class="grid"><section class="card wide"><h3>TODAY'S BOARD</h3>${gameRows(d.games||[])}</section><section class="card"><h3>POWER FIVE</h3>${(d.power||[]).map(x=>`<div class="rank"><strong>${x.rank}</strong><span><b>${esc(x.team)}</b><small>${esc(x.record)}</small></span><em>${esc(x.strength)}</em></div>`).join("")}</section><section class="card full"><h3>LEAGUE LEADERS</h3>${leaderStrip()}</section></div>`)}

function teams(){shell("Teams",`<div class="hero"><div><span class="ey">CLUB INTELLIGENCE</span><h1>MLB <em>TEAMS.</em></h1></div><select id="teamSel" class="select"><option value="">Choose one of 30 MLB teams</option>${state.teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join("")}</select></div><div id="teamBody" class="grid"><section class="card full"><h3>LEAGUE STANDINGS</h3>${standingsTable(state.standings)}</section></div>`);$("#teamSel").onchange=async e=>{if(!e.target.value)return;let [r,st]=await Promise.all([api("/api/mlb/roster?team="+e.target.value),api("/api/mlb/teamstats?team="+e.target.value)]);let tm=state.teams.find(x=>String(x.id)===e.target.value);$("#teamBody").innerHTML=`<section class="card full"><h3>${esc(tm?.name)} · ${esc(tm?.division)}</h3><div class="statgrid">${statsCards(st.groups?.hitting,["gamesPlayed","plateAppearances","atBats","runs","hits","doubles","triples","homeRuns","rbi","baseOnBalls","strikeOuts","stolenBases","avg","obp","slg","ops"])}</div></section><section class="card half"><h3>ACTIVE ROSTER</h3>${(r.players||[]).map(p=>`<div class="play clickable" onclick="openPlayer(\'${p.id}\')"><b>${esc(p.name)}</b> · ${esc(p.position)} · #${esc(p.number)}</div>`).join("")}</section><section class="card half"><h3>PITCHING</h3><div class="statgrid">${statsCards(st.groups?.pitching,["gamesPlayed","gamesStarted","wins","losses","era","inningsPitched","hits","runs","earnedRuns","homeRuns","baseOnBalls","strikeOuts","whip","saves","saveOpportunities"])}</div></section><section class="card full"><h3>CLUB STAT PROFILE</h3><div class="metricbars">${metricProfile(st.groups?.hitting,["runs","hits","doubles","triples","homeRuns","rbi","baseOnBalls","stolenBases"])}</div></section>`}}
function metricProfile(o,ks){o=o||{};let vals=ks.map(k=>[k,num(o[k])]).filter(x=>x[1]!=null),mx=Math.max(1,...vals.map(x=>x[1]));return vals.length?vals.map(([k,v])=>`<div class="metric"><span>${esc(k.replace(/([A-Z])/g," $1").toUpperCase())}</span><div class="track"><i style="width:${Math.max(2,v/mx*100)}%"></i></div><b>${esc(v)}</b></div>`).join(""):'<div class="empty">Stat profile building from verified team data.</div>'}
function statsCards(o,ks){o=o||{};return ks.filter(k=>o[k]!=null).map(k=>`<div class="stat"><span>${esc(k.replace(/([A-Z])/g," $1").toUpperCase())}</span><b>${esc(o[k])}</b></div>`).join("")||'<div class="empty">No verified season stats returned.</div>'}
async function recap(){shell("Weekly Recap",`<div class="loading">BUILDING 7-DAY RECAP…</div>`);let end=new Date(),start=new Date(Date.now()-6*86400000),fmt=d=>d.toISOString().slice(0,10);let r=await api(`/api/mlb/schedule-range?start=${fmt(start)}&end=${fmt(end)}`);let finals=(r.days||[]).flatMap(d=>(d.games||[]).map(g=>({...g,day:d.date}))).filter(g=>g.abstract==="Final");shell("Weekly Recap",`<div class="hero"><div><span class="ey">ATLAS / LAST 7 DAYS</span><h1>WEEKLY <em>RECAP.</em></h1><p>Completed MLB games from the last seven calendar days.</p></div><span class="tag">${finals.length} FINALS</span></div><div class="grid">${finals.length?finals.map(g=>`<section class="card"><span class="tag">${esc(g.day)}</span><h3>${esc(g.away?.name)} @ ${esc(g.home?.name)}</h3><div class="big">${esc(g.away?.score)} — ${esc(g.home?.score)}</div><p class="muted">${esc(g.venue)}</p><button class="action" onclick="openGame('${g.id}')">GAME COMMAND</button></section>`).join(""):'<section class="card full empty">No completed games returned in this window.</section>'}</div>`)}
async function ai(){let top=[...state.standings].sort((a,b)=>Number(b.pct)-Number(a.pct)).slice(0,10);let p;try{p=await api("/api/mlb/power")}catch{p={teams:[]}}shell("ATLAS AI",`<div class="hero"><div><span class="ey">GEMINI × VERIFIED ATLAS EVIDENCE</span><h1>ATLAS <em>AI.</em></h1><p>Ask baseball questions grounded in MLB data and the ATLAS archive. Missing evidence stays missing.</p></div></div><div class="grid"><section class="card full"><div class="askrow"><input id="aiq" class="searchbox" placeholder="Ask ATLAS about teams, players, trends, today's games…"><button class="action" onclick="askMLB()">ASK ATLAS</button></div><div id="aianswer" class="aianswer">ATLAS is ready.</div></section><section class="card half"><h3>ATLAS POWER SIGNAL</h3>${(p.teams||[]).slice(0,10).map(x=>`<div class="rank"><strong>${x.rank}</strong><span><b>${esc(x.team)}</b><small>${esc(x.record)} · ${esc(x.recent_games)} archived recent games</small></span><em>${esc(x.strength)}</em></div>`).join("")}</section><section class="card half"><h3>VERIFIED LEADERS</h3>${leaderStrip()}</section></div>`)}
async function askMLB(){let q=$("#aiq")?.value.trim();if(!q)return;let out=$("#aianswer");out.textContent="ATLAS is reasoning from verified baseball evidence…";try{let r=await fetch("/api/mlb/ai/ask",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q})});let x=await r.json();out.textContent=x.answer||x.error||"No answer returned."}catch(e){out.textContent=e.message}}
function leaderStrip(){let cats=[["homeRuns","HOME RUNS"],["battingAverage","AVG"],["runsBattedIn","RBI"],["stolenBases","SB"],["earnedRunAverage","ERA"],["strikeouts","K"],["saves","SAVES"]];return `<div class="leaders">${cats.map(([k,n])=>{let x=leaderRows(k)[0];return `<button class="leader" ${x?.playerId?`onclick="openPlayer('${x.playerId}')"`:""}><span>${n}</span><b>${esc(x?.player)}</b><strong>${esc(x?.value)}</strong><small>${esc(x?.team)}</small></button>`}).join("")}</div>`}
async function openPlayer(id){let [x,h]=await Promise.all([api("/api/mlb/player?id="+id),api("/api/mlb/player-history?id="+id)]);state.player=x.player;if(state.player)state.player.history=h.games||[];playerDrawer()}
function playerDrawer(){let p=state.player;if(!p)return;let st=p.stats||{}, hit=st.hitting||{}, pit=st.pitching||{};document.body.insertAdjacentHTML("beforeend",`<div class="drawerback" id="drawer" onclick="if(event.target===this)this.remove()"><section class="drawer"><button class="close" onclick="document.getElementById('drawer').remove()">×</button><span class="ey">PLAYER PROFILE</span><h2>${esc(p.name)}</h2><p>${esc(p.team)} · ${esc(p.position)} ${p.number?"· #"+esc(p.number):""}</p><div class="statgrid">${statsCards(Object.keys(hit).length?hit:pit,Object.keys(hit).length?["gamesPlayed","atBats","runs","hits","homeRuns","rbi","stolenBases","avg","obp","slg","ops"]:["gamesPlayed","gamesStarted","wins","losses","era","inningsPitched","strikeOuts","whip","saves"])}</div><p class="muted">Bats: ${esc(p.batSide)} · Throws: ${esc(p.pitchHand)}</p><h3>ATLAS ARCHIVED GAME LOG</h3>${(p.history||[]).slice(0,10).map(g=>`<div class="play"><b>${esc(g.game_date)} · ${esc(g.team)} · ${esc(g.kind)}</b><br>${Object.entries(g.stats||{}).filter(([k,v])=>["hits","atBats","homeRuns","rbi","runs","inningsPitched","strikeOuts","earnedRuns"].includes(k)&&v!=null).map(([k,v])=>`${esc(k)} ${esc(v)}`).join(" · ")}</div>`).join("")||'<div class="empty">History builds as ATLAS archives completed games.</div>'}</section></div>`)}

render();