const $=s=>document.querySelector(s),V=$("#view"),pages=[["home","Home","⌂"],["games","Games","⚾"],["teams","Teams","◆"],["graphs","Game Graphs","⌁"],["recap","Weekly Recap","▤"],["ai","ATLAS AI","A"]];
let state={page:"home",games:[],teams:[],standings:[],leaders:{},game:null,team:null,player:null};
const esc=x=>String(x??"—").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const api=async u=>{let r=await fetch(u,{cache:"no-store"}),x=await r.json();if(!r.ok||x?.ok===false)throw new Error(x?.error||("Request failed "+r.status));return x};
$("#nav").innerHTML=pages.map(([id,n,ic])=>`<button data-page="${id}" data-icon="${ic}">${n}</button>`).join("");
$("#nav").onclick=e=>{let b=e.target.closest("button");if(b){state.page=b.dataset.page;render()}};
setInterval(()=>$("#clock").textContent=new Date().toLocaleString(),1000);
function shell(name,body){$("#title").textContent=name.toUpperCase();document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===state.page));V.innerHTML=`<div class="page">${body}</div>`}
const gameRows=gs=>gs.length?gs.map(g=>`<div class="game" onclick="openGame('${g.id}')"><div class="team"><b>${esc(g.away?.name)}</b><div class="muted">${esc(g.away?.probable||"")}</div></div><div><div class="score">${esc(g.away?.score??"—")} · ${esc(g.home?.score??"—")}</div><span class="tag">${esc(g.inningState&&g.inning?g.inningState+" "+g.inning:g.status)}</span></div><div class="team"><b>${esc(g.home?.name)}</b><div class="muted">${esc(g.home?.probable||"")}</div></div></div>`).join(""):`<div class="empty">No MLB games returned for this date.</div>`;
async function ensure(){if(!state.games.length){let [g,t,s,l]=await Promise.all([api("/api/mlb/schedule"),api("/api/mlb/teams"),api("/api/mlb/standings"),api("/api/mlb/leaders")]);state.games=g.games||[];state.teams=t.teams||[];state.standings=s.standings||[];state.leaders=l.leaders||{}}}
async function render(){shell(state.page,`<div class="loading">LOADING VERIFIED MLB DATA…</div>`);try{await ensure(); if(state.page==="home")home();if(state.page==="games")games();if(state.page==="teams")teams();if(state.page==="graphs")graphs();if(state.page==="recap")recap();if(state.page==="ai")ai()}catch(e){shell(state.page,`<div class="empty">MLB data could not load right now.<br>${esc(e.message)}</div>`)}}
function home(){let live=state.games.filter(g=>g.abstract==="Live"),finals=state.games.filter(g=>g.abstract==="Final");shell("Home",`<div class="hero"><div><span class="ey">MLB ATLAS / BASEBALL COMMAND</span><h1>BASEBALL<br><em>COMMAND.</em></h1><p>Verified MLB game data, standings, teams and live game state.</p></div><span class="tag">${live.length} LIVE</span></div><div class="grid"><section class="card wide"><h3>TODAY'S GAMES</h3>${gameRows(state.games)}</section><section class="card"><h3>LEAGUE PULSE</h3><div class="statgrid"><div class="stat"><span>GAMES</span><b>${state.games.length}</b></div><div class="stat"><span>LIVE</span><b>${live.length}</b></div><div class="stat"><span>FINAL</span><b>${finals.length}</b></div><div class="stat"><span>TEAMS</span><b>${state.teams.length}</b></div></div><p class="muted">Source: MLB Stats API. Missing values stay missing.</p></section><section class="card full"><h3>DIVISION STANDINGS</h3>${standingsTable(state.standings)}</section><section class="card full"><h3>MLB LEADERS</h3>${leaderStrip()}</section></div>`)}
function games(){shell("Games",`<div class="hero"><div><span class="ey">SCOREBOARD</span><h1>MLB <em>GAMES.</em></h1></div><input id="date" class="select" type="date"></div><div class="card full" id="gamesList">${gameRows(state.games)}</div>`);$("#date").onchange=async e=>{let x=await api("/api/mlb/schedule?date="+e.target.value);state.games=x.games||[];$("#gamesList").innerHTML=gameRows(state.games)}}
async function openGame(id){state.game=await api("/api/mlb/game?id="+id);state.page="graphs";graphs()}
function diamond(g){let b=g?.bases||{};return `<div class="diamond"><div class="field"></div><i class="base b1 ${b.first?"on":""}"></i><i class="base b2 ${b.second?"on":""}"></i><i class="base b3 ${b.third?"on":""}"></i><i class="base home"></i></div><div class="count"><b>${esc(g?.inningState)} ${esc(g?.inningOrdinal||g?.inning)}</b><br>B ${esc(g?.balls)} · S ${esc(g?.strikes)} · O ${esc(g?.outs)}</div>`}
function graphs(){let g=state.game;if(!g){shell("Game Graphs",`<div class="hero"><div><span class="ey">DIAMOND COMMAND CENTER</span><h1>GAME <em>GRAPHS.</em></h1><p>Select a game to open the live baseball command center.</p></div></div><div class="card full">${gameRows(state.games)}</div>`);return}let inn=g.innings||[];shell("Game Graphs",`<div class="hero"><div><span class="ey">GAME ${esc(g.id)} / ${esc(g.status)}</span><h1>${esc(g.away?.abbr)} ${esc(g.away?.runs)} <em>—</em> ${esc(g.home?.runs)} ${esc(g.home?.abbr)}</h1><p>${esc(g.venue)}</p></div><button class="action" onclick="refreshGame()">REFRESH</button></div><div class="grid"><section class="card">${diamond(g)}<p class="muted">At bat: ${esc(g.batter)}<br>Pitching: ${esc(g.pitcher)}</p></section><section class="card wide"><h3>LINE SCORE</h3><table class="lines"><tr><th>TEAM</th>${inn.map(x=>`<th>${esc(x.num)}</th>`).join("")}<th>R</th><th>H</th><th>E</th></tr><tr><td>${esc(g.away?.abbr)}</td>${inn.map(x=>`<td>${esc(x.away?.runs??"")}</td>`).join("")}<td>${esc(g.away?.runs)}</td><td>${esc(g.away?.hits)}</td><td>${esc(g.away?.errors)}</td></tr><tr><td>${esc(g.home?.abbr)}</td>${inn.map(x=>`<td>${esc(x.home?.runs??"")}</td>`).join("")}<td>${esc(g.home?.runs)}</td><td>${esc(g.home?.hits)}</td><td>${esc(g.home?.errors)}</td></tr></table></section><section class="card half"><h3>RECENT PLAYS</h3>${(g.plays||[]).slice(-10).reverse().map(p=>`<div class="play"><b>${esc(p.half)} ${esc(p.inning)} · ${esc(p.event)}</b><br>${esc(p.description)}</div>`).join("")||'<div class="empty">No captured plays.</div>'}</section><section class="card half"><h3>PLAYER LINES</h3>${playerLines(g)}</section></div>`)}
async function refreshGame(){if(state.game){state.game=await api("/api/mlb/game?id="+state.game.id);graphs()}}
function playerLines(g){let h=(g.hitters||[]).filter(x=>x.stats?.atBats||x.stats?.hits).slice(0,12);return h.map(x=>`<div class="play"><b>${esc(x.name)} · ${esc(x.team)}</b><br>${esc(x.stats.hits)} H · ${esc(x.stats.atBats)} AB · ${esc(x.stats.runs)} R · ${esc(x.stats.rbi)} RBI · ${esc(x.stats.homeRuns)} HR</div>`).join("")||'<div class="empty">No verified batting lines yet.</div>'}
function standingsTable(r){return `<table class="lines"><tr><th>TEAM</th><th>W</th><th>L</th><th>PCT</th><th>GB</th><th>STRK</th></tr>${r.map(x=>`<tr><td>${esc(x.team)}</td><td>${esc(x.wins)}</td><td>${esc(x.losses)}</td><td>${esc(x.pct)}</td><td>${esc(x.gb)}</td><td>${esc(x.streak)}</td></tr>`).join("")}</table>`}
function teams(){shell("Teams",`<div class="hero"><div><span class="ey">CLUB INTELLIGENCE</span><h1>MLB <em>TEAMS.</em></h1></div><select id="teamSel" class="select"><option value="">Choose one of 30 MLB teams</option>${state.teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join("")}</select></div><div id="teamBody" class="grid"><section class="card full"><h3>LEAGUE STANDINGS</h3>${standingsTable(state.standings)}</section></div>`);$("#teamSel").onchange=async e=>{if(!e.target.value)return;let [r,st]=await Promise.all([api("/api/mlb/roster?team="+e.target.value),api("/api/mlb/teamstats?team="+e.target.value)]);let tm=state.teams.find(x=>String(x.id)===e.target.value);$("#teamBody").innerHTML=`<section class="card full"><h3>${esc(tm?.name)} · ${esc(tm?.division)}</h3><div class="statgrid">${statsCards(st.groups?.hitting,["gamesPlayed","runs","hits","homeRuns","avg","obp","slg","ops"])}</div></section><section class="card half"><h3>ACTIVE ROSTER</h3>${(r.players||[]).map(p=>`<div class="play clickable" onclick="openPlayer(\'${p.id}\')"><b>${esc(p.name)}</b> · ${esc(p.position)} · #${esc(p.number)}</div>`).join("")}</section><section class="card half"><h3>PITCHING</h3><div class="statgrid">${statsCards(st.groups?.pitching,["era","wins","losses","strikeOuts","whip","saves","inningsPitched"])}</div></section>`}}
function statsCards(o,ks){o=o||{};return ks.filter(k=>o[k]!=null).map(k=>`<div class="stat"><span>${esc(k.replace(/([A-Z])/g," $1").toUpperCase())}</span><b>${esc(o[k])}</b></div>`).join("")||'<div class="empty">No verified season stats returned.</div>'}
async function recap(){shell("Weekly Recap",`<div class="loading">BUILDING 7-DAY RECAP…</div>`);let end=new Date(),start=new Date(Date.now()-6*86400000),fmt=d=>d.toISOString().slice(0,10);let r=await api(`/api/mlb/schedule-range?start=${fmt(start)}&end=${fmt(end)}`);let finals=(r.days||[]).flatMap(d=>(d.games||[]).map(g=>({...g,day:d.date}))).filter(g=>g.abstract==="Final");shell("Weekly Recap",`<div class="hero"><div><span class="ey">ATLAS / LAST 7 DAYS</span><h1>WEEKLY <em>RECAP.</em></h1><p>Completed MLB games from the last seven calendar days.</p></div><span class="tag">${finals.length} FINALS</span></div><div class="grid">${finals.length?finals.map(g=>`<section class="card"><span class="tag">${esc(g.day)}</span><h3>${esc(g.away?.name)} @ ${esc(g.home?.name)}</h3><div class="big">${esc(g.away?.score)} — ${esc(g.home?.score)}</div><p class="muted">${esc(g.venue)}</p><button class="action" onclick="openGame('${g.id}')">GAME COMMAND</button></section>`).join(""):'<section class="card full empty">No completed games returned in this window.</section>'}</div>`)}
function ai(){let top=[...state.standings].sort((a,b)=>Number(b.pct)-Number(a.pct)).slice(0,10);shell("ATLAS AI",`<div class="hero"><div><span class="ey">ATLAS / BASEBALL INTELLIGENCE</span><h1>ATLAS <em>AI.</em></h1><p>Version 1.0 uses verified MLB standings and game evidence. Predictive baseball models come after the MLB archive has enough stored games.</p></div></div><div class="grid"><section class="card half"><h3>LEAGUE SIGNAL</h3>${top.map((x,i)=>`<div class="play"><b>${i+1}. ${esc(x.team)}</b><br>${esc(x.wins)}-${esc(x.losses)} · ${esc(x.pct)}</div>`).join("")}</section><section class="card half"><h3>LEAGUE LEADERS</h3>${leaderStrip()}<p class="muted">These are verified statistical leaders, not ATLAS award predictions.</p></section><section class="card full"><h3>ATLAS BASEBALL MODEL STATUS</h3><div class="statusgrid"><div><span>GAME DATA</span><b>ACTIVE</b></div><div><span>TEAM DATA</span><b>ACTIVE</b></div><div><span>PLAYER DATA</span><b>ACTIVE</b></div><div><span>LIVE FEED</span><b>ACTIVE</b></div><div><span>LONG-TERM ARCHIVE</span><b>BUILDING NEXT</b></div><div><span>PROJECTION MODEL</span><b>WAITING FOR ARCHIVE</b></div></div><p class="muted">ATLAS does not substitute made-up values for unavailable Statcast or historical model evidence.</p></section></div>`)}

function leaderStrip(){let cats=[["homeRuns","HOME RUNS"],["battingAverage","AVG"],["runsBattedIn","RBI"],["stolenBases","SB"],["earnedRunAverage","ERA"],["strikeouts","K"],["saves","SAVES"]];return `<div class="leaders">${cats.map(([k,n])=>{let x=(state.leaders[k]||[])[0];return `<button class="leader" ${x?.playerId?`onclick="openPlayer('${x.playerId}')"`:""}><span>${n}</span><b>${esc(x?.player)}</b><strong>${esc(x?.value)}</strong><small>${esc(x?.team)}</small></button>`}).join("")}</div>`}
async function openPlayer(id){let x=await api("/api/mlb/player?id="+id);state.player=x.player;playerDrawer()}
function playerDrawer(){let p=state.player;if(!p)return;let st=p.stats||{}, hit=st.hitting||{}, pit=st.pitching||{};document.body.insertAdjacentHTML("beforeend",`<div class="drawerback" id="drawer" onclick="if(event.target===this)this.remove()"><section class="drawer"><button class="close" onclick="document.getElementById('drawer').remove()">×</button><span class="ey">PLAYER PROFILE</span><h2>${esc(p.name)}</h2><p>${esc(p.team)} · ${esc(p.position)} ${p.number?"· #"+esc(p.number):""}</p><div class="statgrid">${statsCards(Object.keys(hit).length?hit:pit,Object.keys(hit).length?["gamesPlayed","atBats","runs","hits","homeRuns","rbi","stolenBases","avg","obp","slg","ops"]:["gamesPlayed","gamesStarted","wins","losses","era","inningsPitched","strikeOuts","whip","saves"])}</div><p class="muted">Bats: ${esc(p.batSide)} · Throws: ${esc(p.pitchHand)}</p></section></div>`)}

render();