
const $=s=>document.querySelector(s), esc=s=>String(s??"—").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const pages=["Home","Games","Teams","Players","Standings","Leaders","GameCast","Analytics","ATLAS Daily","ATLAS AI","Data Doctor"];
let S={page:"Home",teams:[],games:[],game:null,team:null};
async function api(u){let r=await fetch(u,{cache:"no-store"}),x=await r.json();if(!r.ok||x.ok===false)throw Error(x.error||"NBA data unavailable");return x}
function nav(){ $("#nav").innerHTML=pages.map(p=>`<button class="${S.page===p?"active":""}" onclick="go('${p}')">${p}</button>`).join("")}
function shell(title,body,sub="NBA ATLAS · VERIFIED PUBLIC DATA"){nav();$("#app").innerHTML=`<div class="page"><section class="hero"><small>${sub}</small><h1>${title}</h1><p>Basketball intelligence built from verified NBA game, team and player feeds. Missing data stays missing. No betting features.</p></section>${body}</div>`;ATLAS60.attach()}
function gameCard(g){let st=g.state==="in"?"live":g.completed?"final":"pre";return `<div class="game" onclick="openGame('${g.id}')"><div class="team"><img src="${g.away?.logo||""}"><b>${esc(g.away?.abbr)}</b><small>${esc(g.away?.record||"")}</small></div><div class="score ${st}">${esc(g.away?.score)} · ${esc(g.home?.score)}<small>${esc(g.status)}</small></div><div class="team"><img src="${g.home?.logo||""}"><b>${esc(g.home?.abbr)}</b><small>${esc(g.home?.record||"")}</small></div></div>`}
async function home(){shell("THE COURT IS LIVE",`<div class="grid"><section class="card wide"><h3>TODAY / NEXT UP</h3><div id="games">${ATLAS62.loading()}</div></section><section class="card"><h3>NBA ATLAS 7.0</h3><div class="metric">30<span>TEAMS</span></div><p>Live scores, rosters, standings, leaders, GameCast and basketball analytics in the ATLAS platform.</p></section><section class="card full"><h3>COURT COMMAND CENTER</h3><div class="court"></div></section></div>`);try{let x=await api("/api/nba/schedule");S.games=x.games;$("#games").innerHTML=x.games.length?x.games.map(gameCard).join(""):ATLAS62.empty("No NBA games on the current scoreboard.","Use Games as the season schedule becomes active.")}catch(e){$("#games").innerHTML=ATLAS62.error(e.message)}}
async function games(){shell("GAMES",`<div class="card full"><h3>NBA SCOREBOARD</h3><input type="date" id="date"><button class="action" onclick="loadDate()">LOAD DATE</button><div id="games">${ATLAS62.loading()}</div></div>`);loadDate()}
async function loadDate(){try{let d=$("#date")?.value,x=await api("/api/nba/schedule"+(d?"?date="+d:""));S.games=x.games;$("#games").innerHTML=x.games.length?x.games.map(gameCard).join(""):ATLAS62.empty("No games found for this date.")}catch(e){$("#games").innerHTML=ATLAS62.error(e.message)}}
async function teams(){shell("TEAMS",`<div class="grid" id="teams">${ATLAS62.loading()}</div>`);try{let x=await api("/api/nba/teams");S.teams=x.teams;$("#teams").innerHTML=x.teams.map(t=>`<section class="card" onclick="openTeam('${t.id}')"><img src="${t.logo||""}" style="width:58px;height:58px;object-fit:contain"><h2>${esc(t.name)}</h2><span class="pill">${esc(t.abbr)}</span></section>`).join("")}catch(e){$("#teams").innerHTML=ATLAS62.error(e.message)}}
async function openTeam(id){try{let [ts,rr]=await Promise.all([api("/api/nba/teams"),api("/api/nba/roster?team="+id)]),t=ts.teams.find(x=>String(x.id)===String(id));S.team=t;shell(t?.name||"TEAM",`<div class="grid"><section class="card"><img src="${t?.logo||""}" style="width:100px"><h2>${esc(t?.abbr)}</h2></section><section class="card wide"><h3>ROSTER</h3>${rr.players.map(p=>`<div class="playerrow" onclick="openPlayer('${p.id}')"><img src="${p.headshot||""}"><b>${esc(p.name)}</b><span>${esc(p.position)}</span><span>#${esc(p.jersey)}</span></div>`).join("")||ATLAS62.empty("Roster unavailable.")}</section></div>`)}catch(e){shell("TEAM",ATLAS62.error(e.message))}}
async function players(){shell("PLAYERS",`<div class="grid"><section class="card full"><h3>PLAYER EXPLORER</h3><p>Select a team, then open any roster player for an NBA ATLAS profile.</p><button class="action" onclick="go('Teams')">OPEN TEAM HUBS</button></section></div>`)}
async function openPlayer(id){try{let x=await api("/api/nba/player?id="+id),p=x.player;$("#drawer").innerHTML=`<div class="drawerback" onclick="if(event.target===this)$('#drawer').innerHTML=''"><section class="drawerpanel"><button class="action" onclick="$('#drawer').innerHTML=''">CLOSE</button><img class="headshot" src="${p.headshot||""}"><small class="eyebrow">NBA PLAYER HUB</small><h1>${esc(p.name)}</h1><div class="tabs"><span class="pill">${esc(p.position)}</span><span class="pill">${esc(p.team)}</span><span class="pill">#${esc(p.jersey)}</span></div><p>${esc(p.height)} · ${esc(p.weight)} · Age ${esc(p.age)}</p><button class="action ask61" data-atlas-prompt="Explain the verified NBA profile for ${esc(p.name)} without inventing missing statistics.">✦ ASK ATLAS</button></section></div>`}catch(e){ATLAS62.notify(e.message,"bad")}}
async function standings(){shell("STANDINGS",`<section class="card full"><h3>NBA STANDINGS</h3><div id="stand">${ATLAS62.loading()}</div></section>`);try{let x=await api("/api/nba/standings");$("#stand").innerHTML=x.standings.map((r,i)=>`<div class="standrow"><img src="${r.logo||""}"><b>${i+1}. ${esc(r.name)}</b><span>${esc(r.stats?.wins||r.stats?.W||"—")} W</span><span>${esc(r.stats?.losses||r.stats?.L||"—")} L</span><span>${esc(r.stats?.winPercent||r.stats?.PCT||"—")}</span></div>`).join("")||ATLAS62.empty("Standings are not populated yet.")}catch(e){$("#stand").innerHTML=ATLAS62.error(e.message)}}
async function leaders(){shell("LEADERS",`<div class="grid" id="leaders">${ATLAS62.loading()}</div>`);try{let x=await api("/api/nba/leaders");$("#leaders").innerHTML=x.categories.slice(0,12).map(c=>`<section class="card"><h3>${esc(c.name)}</h3>${c.leaders.slice(0,5).map((p,i)=>`<div class="leader" onclick="openPlayer('${p.id}')"><img src="${p.headshot||""}"><b>${i+1}. ${esc(p.name)} <small>${esc(p.team)}</small></b><strong>${esc(p.value)}</strong></div>`).join("")}</section>`).join("")||ATLAS62.empty("Season leaders are not populated yet.")}catch(e){$("#leaders").innerHTML=ATLAS62.error(e.message)}}
async function openGame(id){try{let x=await api("/api/nba/game?id="+id);S.game=x;S.page="GameCast";render()}catch(e){ATLAS62.notify(e.message,"bad")}}
function gamecast(){let x=S.game;if(!x){shell("GAMECAST",`<section class="card full">${ATLAS62.empty("Choose a game first.","Open Games and select an NBA matchup.")}</section>`);return}let g=x.game,ev=(x.plays||[]).map(p=>({period:p.period,text:(p.clock?p.clock+" · ":"")+(p.text||"")}));shell("GAMECAST 2.0",`<div class="grid"><section class="card wide"><h3>LIVE COURT</h3><div class="court"></div>${ATLAS60.eventTimeline(ev)}</section><section class="card"><h3>GAME STATE</h3><div class="metric">${esc(g?.period||"—")}<span>PERIOD</span></div><div class="metric">${esc(g?.clock||"—")}<span>CLOCK</span></div><button class="action ask61" data-atlas-prompt="Explain this NBA game using only verified ATLAS game data.">✦ EXPLAIN GAME</button></section><section class="card full"><h3>PLAYER BOX SCORE</h3>${(x.players||[]).map(p=>`<div class="playerrow" onclick="openPlayer('${p.id}')"><img src="${p.headshot||""}"><b>${esc(p.name)} <small>${esc(p.team)}</small></b><span>${esc(p.stats?.PTS||p.stats?.points||"—")} PTS</span><span>${esc(p.stats?.REB||p.stats?.rebounds||"—")} REB</span></div>`).join("")||ATLAS62.empty("Verified player box score is not available yet.")}</section></div>`)}
async function analytics(){shell("ANALYTICS LAB",`<div class="grid"><section class="card"><h3>PACE / EFFICIENCY</h3>${ATLAS62.empty("Historical NBA archive is building.","7.0 does not fabricate trend lines before stored game history exists.")}</section><section class="card"><h3>PLAYER IMPACT</h3>${ATLAS62.empty("Impact models require verified NBA game rows.")}</section><section class="card"><h3>TEAM FORM</h3>${ATLAS62.empty("Team-form intelligence will activate from stored verified history.")}</section><section class="card full"><h3>VISUAL LAB</h3><div class="court"></div></section></div>`)}
async function daily(){shell("ATLAS DAILY",`<div class="grid"><section class="card wide"><h3>NBA TODAY</h3><div id="daily">${ATLAS62.loading()}</div></section><section class="card"><h3>INTELLIGENCE RULE</h3><p>Only verified scoreboard and season data are surfaced. ATLAS does not create fake storylines when the season feed is empty.</p></section></div>`);try{let x=await api("/api/nba/schedule");$("#daily").innerHTML=x.games.length?x.games.map(gameCard).join(""):ATLAS62.empty("No NBA game stories yet.")}catch(e){$("#daily").innerHTML=ATLAS62.error(e.message)}}
function ai(){shell("ATLAS AI",`<div class="grid"><section class="card wide"><h3>BASKETBALL BRAIN</h3><textarea id="aiq" style="width:100%;min-height:110px;background:#ffffff05;color:white;border:1px solid #ffffff12;border-radius:10px;padding:12px" placeholder="Ask ATLAS about the verified NBA data shown in the app…"></textarea><p>NBA-specific Gemini answering will be expanded after the NBA archive has enough verified evidence. Current ATLAS AI will not invent unavailable NBA stats.</p></section><section class="card"><h3>SOURCE POLICY</h3><span class="pill">ESPN NBA PUBLIC FEEDS</span><span class="pill">NO BETTING</span><span class="pill">NO FABRICATION</span></section></div>`)}
async function doctor(){shell("DATA DOCTOR",`<section class="card full"><h3>NBA SOURCE HEALTH</h3><div id="diag">${ATLAS62.loading()}</div></section>`);try{let x=await api("/api/nba/diagnostics");$("#diag").innerHTML=Object.entries(x.checks).map(([k,v])=>`<div class="standrow"><span></span><b>${k.toUpperCase()}</b><span>${v.ok?"PASS":"CHECK"}</span><span>${esc(v.count??"")}</span><span></span></div>`).join("")+ATLAS60.receipt("DATA RULES",x.rules||[])}catch(e){$("#diag").innerHTML=ATLAS62.error(e.message)}}
function go(p){ATLAS54.stopAll();S.page=p;render()}
function render(){({Home:home,Games:games,Teams:teams,Players:players,Standings:standings,Leaders:leaders,GameCast:gamecast,Analytics:analytics,"ATLAS Daily":daily,"ATLAS AI":ai,"Data Doctor":doctor}[S.page]||home)()}
$("#search").addEventListener("keydown",async e=>{if(e.key!=="Enter")return;let q=e.target.value.trim();if(!q)return;try{let x=await api("/api/nba/search?q="+encodeURIComponent(q));shell("SEARCH",`<section class="card full"><h3>RESULTS</h3>${x.results.map(r=>`<div class="playerrow" ${r.type==="team"?`onclick="openTeam('${r.id}')"`:""}><span></span><b>${esc(r.name)}</b><span>${esc(r.abbr||r.type)}</span><span></span></div>`).join("")||ATLAS62.empty("No verified NBA results found.")}</section>`)}catch(err){ATLAS62.notify(err.message,"bad")}})
setInterval(()=>$("#clock").textContent=new Date().toLocaleString(),1000);render();
